### ISSUE TITLE
RadlistView feature request - to abort a reoder when drop is outside listview

### ISSUE THREAD

**Issue by sflament** [telerik/nativescript-ui-samples#101]
Hello,

I would like to abort a ongoing reorder if the user release his action outside the listview.
May be, it could be interesting to specify the behavior ; onReleaseOutside = "perform" or "abort"

This feature could be useful to select an item and perform an specific action if the item is dropped toward a component aside the listview. Then the ReorderEvent should give the component on which the user had released his finger.

Stephane

**Comment by ginev** [comment]
@sflament, thanks for the feedback!
We will consider your suggestion. Do you want also to have the item visually dragged outside the listview or simply have it animated back to its original place once the drag coordinates leave the list area?

**Comment by sflament** [comment]
Hello,

Thank's for considering this suggestion ! :-)
I would like to have the item dragged outside the listview.

I need also to move an item from one radlistview to an another radlistview.
May be this first stage will be a starting point for this purpose.

For people interesting with theses features (outside drop, and drag/drop
between listviews, I'm trying to perform it here :
https://github.com/sflament/nativescript-drag-between-listviews/blob/radlistview/README.md


2016-07-12 14:27 GMT+02:00 Deyan Ginev <notifications@github.com>:

**Comment by sflament** [comment]
Hello, Ginev ? any news on this ?
    2016-07-12 14:27 GMT+02:00 Deyan Ginev notifications@github.com:
    @sflament https://github.com/sflament, thanks for the feedback!
    We will consider your suggestion. ...

Sincerely,

**Comment by ginev** [comment]
This issue was moved to telerik/nativescript-ui-feedback#119
