### ISSUE TITLE
ListView is unusable with Webpack

### ISSUE THREAD

**Issue by inferno001** [telerik/nativescript-ui-samples#104]
I am unable to use the ListViewComponent with Webpack because of a strange import statement.

In `listview/angular/listview-directives.js` you are using a similar import like `import * as a from './..'`
Webpack will look into the `package.json` and not find the entry file (listview.js).

Otherwise in the sidedrawer you are writing `import * as b from './../sidedrawer'` and Webpack will try to resolve all given extension and at some point hit `sidedrawer.ios.js` or `sidedrawer.android.js`

So maybe you can consider this and change the import to be like in the sidedrawer.

Thank you :)

**Comment by leocaseiro** [comment]
I confirm the same issue!

I tested with Angular and on Android.

As I mentioned [here](https://github.com/NativeScript/nativescript-dev-webpack/issues/8#issuecomment-237451023) If you rename from `listview.android.js` to `listview.js`, it'll work for Android. However, ios won't work...

**Comment by adisoftbn** [comment]
I have the same problem, and I haven't found a fix yet...

if i use :

import { LISTVIEW_DIRECTIVES } from 'nativescript-telerik-ui/listview/angular';

I get the same error with unable to find module from "./..".

**Comment by Karnich** [comment]
chart have the same problem... solved by replacing **./../** with **./../chart**
