### ISSUE TITLE
RadListView multiple Slide issues

### ISSUE THREAD

**Issue by NathanaelA** [telerik/nativescript-ui-samples#107]
@ginev -

Not sure if any of issues are on iOS also; as I haven't had a chance to test iOS yet.   But using NS 2.1, w/ 1.2.0 of the NS-Telerik-UI on Android 4.4 geny emulator.

So I here is what I want to do; swipe from the right and show a "Delete" button inside the list view row.
I do NOT have anything to swipe from the other side; so 

1. I set swipeLimits.left = 68 * screenres;  swipeLimits.threshold = 60 * screenres.
-> Will allow me to swipe from the right of the screen; but the bar jumps back, no matter what values I set the left / threshold the screen jumps back to the same position obscuring part of the button.
![slide1](https://cloud.githubusercontent.com/assets/850871/17045509/7030dfa4-4f8f-11e6-8f2e-b0bf35982bb2.gif)

2. If I set swipeLimits.right = 0; to the above code then it won't even "lock".

3. If I set swipeLimits.right = 68*screenres; then it actually locks where I want it to; but then now I can swipe from the left side of the screen to the right and show a nice empty spot.  ;-(

4. When you "undo" the slide by trying to drag it back; it looks horrible and very janky:
-- Please note this occurs on BOTH sides of the screen; it appears like the slid control jumps to original position, then back to its slid position before starting to slide it back.  In addition it appears you hide the underlying layout BEFORE the slide is done...   It looks very bad.
![slide2](https://cloud.githubusercontent.com/assets/850871/17045526/99748c8a-4f8f-11e6-9856-ffb495b6e3dc.gif) 

5. The buttons on the slid part of the interface is not clickable when it has been slid, nor does this part of the slid interface seem to register any observable updates...   

6. The itemSwipeProgressStarted event only occasionally has the args.object; most the time it was missing.

7. args.object (when present) never points to the actual sliding layout; but the new layout that is now going to show; how do I get access to the sliding layout. -- I would like to show those buttons disabled when slid since you can't click them.

(6 & 7 are issues in v1.1.1, I just upgraded to v1.2; and so I haven't retested 6 & 7, but if you haven't fixed them in the v1.2 update; then they are still issues...)

**Comment by ginev** [comment]
@NathanaelA I am closing this one as we moved the discussion in the support forums.
