### ISSUE TITLE
Switcher in Samples

### ISSUE THREAD

**Issue by paranoid-android** [telerik/nativescript-ui-samples#11]
Hello,

I downloaded Telerik UI for iOS sample app. In the app, do the following:

1. Choose "Financial Indicators" on the "Chart" view.
2. Click "swipe up to see more".

The app view changes to a "switcher" type view. It has "Financial Indicators", "Multiple Axes", "Financial Charts", etc. in a view that gives you a preview of each. Is this a control that allows this switcher view? Or, was this hand-coded? If its a control, 

1. What control is it
2. How do you activate "switcher" mode.?

**Comment by ginev** [comment]
Hi @paranoid-android,

I think you are refering to the wrong forum here as the native Telerik UI for iOS suite has its own support forums where you will be taken care of:

http://www.telerik.com/forums/ios
