### ISSUE TITLE
Question: RadListView clicking in empty space

### ISSUE THREAD

**Issue by NathanaelA** [telerik/nativescript-ui-samples#111]
@ginev,

Since there is no source to the actual underlying control, I can't really look myself...

Is there anyway to detect a click in the empty space if there is few or no items in the listview?

**Comment by ginev** [comment]
@NathanaelA I would handle the `tap` event of the View itself (from which `RadListView`) inherits. This should come out-of-the-box from the View class. Other option would be to handle the `tap` event of the root layout element that holds `RadListView`.

**Comment by NathanaelA** [comment]
I'm going to close this one as it got moved to the support forums; but this solution doesn't seem to work either...

**Comment by ginev** [comment]
@NathanaelA: here's a code snippet that implements this for Android:

```TypeScript
export function onPageLoaded(args) {
    var page = args.object;
    page.bindingContext = new viewModel.ViewModel();
    if (applicationModule.android) {
        var radListView = page.getViewById("radListView");
        var nativeView = radListView.android.getChildAt(0);
        console.log("ListView: " + radListView.android.getChildAt(0));
 
 
        nativeView.setOnTouchListener(new android.view.View.OnTouchListener({
            onTouch: function (v, event) {
                if (event.getAction() == android.view.MotionEvent.ACTION_DOWN
                    && nativeView.findChildViewUnder(event.getX(), event.getY()) == null) {
                        console.log("TOUCH OUTSIDE ITEMS");
                    return true;
                }
                return false;
            }
 
        }));
    }
}
```
