### ISSUE TITLE
SideDrawer stretch across the screen height

### ISSUE THREAD

**Issue by traktraktrugui** [telerik/nativescript-ui-samples#112]
Is there any way to this, stretch the drawer til the screen top border?

How it's | How could be
--------- | ----------------
![drawer01](https://cloud.githubusercontent.com/assets/5555338/17267477/afa7637c-55e0-11e6-91d7-21959264dc23.png) | ![drawer02](https://cloud.githubusercontent.com/assets/5555338/17267479/b33803fc-55e0-11e6-9cfd-9c10c00599e2.png)

[Gmail](https://lh3.ggpht.com/xq5BEIHWBYcbLNIji4Pjdx3gIlscoC0fHxYlG84TPFCxxVSMnCTJbDZ5J47lnVMH7vU=h900-rw) and Play Store app works like second way.

_I don't know if this is the right place to put this issue, but npm package links to here._

**Comment by VladimirAmiorkov** [comment]
Hi @traktraktrugui ,

You can achieve "over the navigation bar" behavior of the RadSideDrawer with the described approach in the documentation [here](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/SideDrawer/getting-started#showing-radsidedrawer-over-the-navigation-baraction-bar). Regarding the Android OS status bar you will beed to do a couple of additional things, you can read [this](https://bradmartin.net/2016/03/10/fullscreen-and-navigation-bar-color-in-a-nativescript-android-app/) guide for more details.
