### ISSUE TITLE
RadListView with Nativescript angular 2

### ISSUE THREAD

**Issue by dotdreaming** [telerik/nativescript-ui-samples#113]
I would like to use the RadListView component in my nativescript angular2 project. The app will be for android and ios. My component templates are in html format, but all of the telerik UI samples are in xml format. I cant get the ListView to work and that might be the reason.
This is the code I have used in my html template:
`<RadListView items="{{ dataItems }}" >
        <RadListView.listViewLayout>
            <ListViewLinearLayout scrollDirection="Vertical"></ListViewLinearLayout>
        </RadListView.listViewLayout>
        <RadListView.itemTemplate>
            <StackLayout orientation="vertical">
                <Label fontSize="20" text="{{ itemName }}"></Label>
                <Label fontSize="14" text="{{ itemDescription }}"></Label>
            </StackLayout>
        </RadListView.itemTemplate>
    </RadListView>`

**Comment by kekelzpekel** [comment]
You are in wrong repo, you should check [here](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/listview/getting-started/listview-getting-started.component.html).
In short you need to bind like this `[items]="dataItems"`
