### ISSUE TITLE
TabView with two RadListView throw an binding error

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-samples#114]
When we have TabView with three tabs and in two of them we have RadListView. When we make navigation to the tab without RadListView and binding error have been throw:

```
Binding: Binding error while setting property items of RadListView(15)@file:///app/test/test.xml:35:12;: TypeError: Cannot read property 'length' of undefined (d:\GitHub\Telerik\node_modules\tns-core-modules\trace\trace.js:160:25)
```

I am attaching [link](https://github.com/tsonevn/bindingError_1052169) to a sample project where this problem could be reproduced.

**Comment by VladimirAmiorkov** [comment]
Hi @tsonevn ,

It looks like the provided sample project is missing couple of files (the **app.js** in [the root](https://github.com/tsonevn/bindingError_1052169/tree/master/app)) and is not runnable. 

Tested the scenario but was not able to observe the mentioned exception:
> TypeError: Cannot read property 'length' of undefined (d:\GitHub\Telerik\node_modules\tns-core-modules\trace\trace.js:160:25)

Could you try to reproduce it with the latest versions:

- NativeScript: 2.3.0
- nativescript-telerik-ui: 1.4.1 

Closing the issue for now, if you continue to experience it please let us know.
