### ISSUE TITLE
Side-drawer: delay when tap on item 

### ISSUE THREAD

**Issue by terreb** [telerik/nativescript-ui-samples#115]
There is a delay in closing the side-drawer when navigating to a new view (any item in side drawer content is clicked). The delay is even higher if the view content is more complex. This causes the user thinks the side menu is unresponsive. 

How to reproduce: clone and run https://github.com/tjvantoll/nativescript-template-drawer, see the difference in responsiveness when the hamburger button is clicked and any side menu item.

Expected result: the drawer closes right away without waiting for the view to be rendered.

**Comment by VladimirAmiorkov** [comment]
Hi @terreb ,

I tried to reproduce the described issue with the latest:

- NativeScript: 2.3.0
- nativescript-telerik-ui: 1.4.1

and the navigation on both iOS and Android is instant and does not experience slow SideDrawer closing.

Closing the issue for now, if you continue to experience this behavior please let us know.
