### ISSUE TITLE
Please remove postinstall

### ISSUE THREAD

**Issue by dvabuzyarov** [telerik/nativescript-ui-samples#117]
For scenario when an application is been built automatically on  a build server the npm install command interrupted with promting email address.

**Comment by ginev** [comment]
@dvabuzyarov This indeed is an issue when automation is involved. We will provide a way to prevent this prompt from happening.

**Comment by ginev** [comment]
@dvabuzyarov there will be a way to disable this prompt by setting up an environmental variable called NSUI_NOPROMPT and setting its value to 1.
