### ISSUE TITLE
Nativescript drawer does not render properly in iOS after device rotating

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-samples#120]
_From @dpdragnev on August 30, 2016 15:13_

I have a NS app which uses a drawer (http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/SideDrawer/overview) as navigation.

One odd thing I noticed is that if I rotate the device landscape and then back to potrait, the drawer's main content gets cut to the point that was visible while the device was in landscape mode. This only happens in iOS. It seems that the drawer content does not redraw after rotating back to portrait. If I navigate to another view (where the drawer is loaded again) everything looks good.

Steps to reproduce:
1. load the view
2. open the drawer - everything looks good
3. close the drawer
4. rotate device in landscape
5. rotate back in portrait
6. open drawer - the content is cut up to the point equivalent of the width of the device (the portion that would be visible when the device is in landscape mode) 

Has anyone experienced this issue? Any ideas on how to solve it?

Related item:  http://stackoverflow.com/questions/39215252/nativescript-drawer-does-not-render-properly-in-ios-after-device-rotating

Thank you.

_Copied from original issue: NativeScript/NativeScript#2646_

**Comment by dpdragnev** [comment]
@tsonevn Any ideas on what could be causing this?  Is this is a bug or I am doing something wrong?

**Comment by VladimirAmiorkov** [comment]
Hi @dpdragnev ,

Sorry for the late response. I tried to reproduce the mentioned steps but was not able to observe the described issue. Could you verify this incorrect behavior with the latest versions of:

- NativeScript: **2.3.0** (tns --version)
- nativescript-telerik-ui **1.4.1**

**Comment by dpdragnev** [comment]
Hello @VladimirAmiorkov,

Thank you for your message.  The strangest thing is that I created a fresh project and tried to reproduce the issues but cannot do it either.  There must be something in my original project that causes this issue.  I will continue testing and will post my findings here.

Thank you.

**Comment by Natalia-Hristova** [comment]
Hello @dpdragnev,

If you have any additional information about this case or need to open another issue, please log it in our dedicated GitHub repository for NativeScript UI issues https://github.com/telerik/nativescript-ui-feedback.
