### ISSUE TITLE
Auto close sidedrawer on navigate.

### ISSUE THREAD

**Issue by sitefinitysteve** [telerik/nativescript-ui-samples#121]
When we click an item in the side drawer to navigate everything on the resulting page becomes unclickable. The fix is to run a close command on the side drawer on page loaded. Is there some way for this to happen automatically?

**Comment by skarlatov** [comment]
Hi Steve, this was reported by another user and has been fixed. The fix will be available in the next release.

**Comment by VladimirAmiorkov** [comment]
Tested this in 1.4.1 and it is working as expected, the SideDrawer is not visible in the new page after the navigation.
