### ISSUE TITLE
Invalid Bundle - A nested bundle contains simulator platform listed in CFBundleSupportedPlatforms Info.plist key.

### ISSUE THREAD

**Issue by nguyenbn** [telerik/nativescript-ui-samples#123]
I was trying to build this for the app store, and just got this error.  

> Dear developer,
> 
> We have discovered one or more issues with your recent delivery for "Intelligent Spaces". To process your delivery, the following issues must be corrected:
> 
> Invalid Bundle - A nested bundle contains simulator platform listed in CFBundleSupportedPlatforms Info.plist key.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.
> 
> Regards,
> 
> The App Store team

I think it might be from this plugin  since I saw iPhoneSimulator listed in the plist file.  Anyhow, I tried modifying it per this post below, but I'm still getting the same error from the Itunes Store.

https://forums.developer.apple.com/thread/62261

I was wondering if anyone here has experienced the same problem and if you have fix for this.

**Comment by nguyenbn** [comment]
I figured it out...I had to change these 3 plist files:

./lib/iOS/TelerikAppFeedback.framework/Info.plist
./lib/iOS/TelerikUI.framework/Info.plist
./lib/iOS/TNSWidgets.framework/Info.plist

**Comment by NathanWalker** [comment]
@nguyenbn you just saved my bacon tonight. Is this something new Apple is starting to enforce (without notice as usual)?. Same app has been built and passing app store auto analyzer for awhile now, then this popped up all sudden. 

/cc @tjvantoll @jlooper

**Comment by Daxito** [comment]
@nguyenbn or @NathanWalker How do you guys modified this file?? It looks like this for me but I don't know how to modify (not an ios dev)

bplist00�	

 "#$%&'*+,\CFBundleNameWDTXcodeYDTSDKNameZDTSDKBuild_CFBundleDevelopmentRegion_CFBundleVersion_BuildMachineOSBuild^DTPlatformName_CFBundlePackageType_CFBundleShortVersionString_CFBundleSupportedPlatforms_CFBundleInfoDictionaryVersion_CFBundleExecutableZDTCompiler_MinimumOSVersion_CFBundleIdentifier^UIDeviceFamily_DTPlatformVersion\DTXcodeBuild_CFBundleSignature_DTPlatformBuildZTNSWidgetsT0731[iphoneos9.3V13E230RenQ1U15F34XiphoneosTFMWKS1.0�!XiPhoneOSS6.0ZTNSWidgets_"com.apple.compilers.llvm.clang.1_0S9.2_org.nativescript.TNSWidgets�()S9.3V7D1014T????5BJT_{�����"7BUjy�������������?Cadfhls-x

**Comment by Daxito** [comment]
I figured it out, just using xcode to edit the plist, thank you!

**Comment by ahalls** [comment]
I'm still trying to get my app to upload and be accepted for the first time.  I received the above error email from the store and then I replaced the CFBundleSupportedPlatforms references in the files list by @nguyenbn ... still no luck ... use the `tns appstore upload` command.  I'm now trying with by using Xcode directly to do the build and upload of the app. I inspected all the plists in the ipa bundle to make sure the CFBundleSupportedPlatforms references where correct.  Keeping my fingers crossed.

**Comment by sp3c1** [comment]
@nguyenbn you just deleted it?

**Comment by Natalia-Hristova** [comment]
Hello guys, 

All issues here will be moved (if they are still valid) and closed because this repository is only for examples.

If you have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thank you in advance!
