### ISSUE TITLE
Xcode 7 fails to submit builds to iTunes because of simulator in Info.plist

### ISSUE THREAD

**Issue by sowrabhbs** [telerik/nativescript-ui-samples#124]
After I upload build to itunes connect,it says build is invalid and got a mail which says
Invalid Bundle - A nested bundle contains simulator platform listed in CFBundleSupportedPlatforms Info.plist key.
Xcode 7

**Comment by ginev** [comment]
@sowrabhbs this has been fixed and an updated version of the plugin will be live on NPMJS soon.
