### ISSUE TITLE
SideDrawer issue

### ISSUE THREAD

**Issue by stevenleeza** [telerik/nativescript-ui-samples#125]
Go to “SideDrawer -> Getting started”.

Tap (quickly) on the left edge of the screen to get the SideDrawer to open slightly (a few pixels) then close again.

Now try to tap the back arrow on the ActionBar - nothing happens.

Problem: The SideDrawer, although closed, still has an invisible layer over the entire screen area so nothing can be tapped. You can get everything back to normal by swipe opening the SideDrawer completely and then tapping/swiping it back to close it.

This issue can be replicated on any app that makes use of the latest Telerik UI SideDrawer component.

**Comment by spstratis** [comment]
I'm running into this same issue, tried removing the gesture abilities but then you can not close the menu by tapping outside the menu. Has anyone found another work around for this??

**Comment by stevenleeza** [comment]
@spstratis If you're only making use of the SideDrawer, you can downgrade to an earlier version.
I'm currently using version 1.1.1. You can just set the version number in your "package.json" file.
If you're using the "DrawerPage" XML element, you'll need to change it back to a "Page" element.

**Comment by Natalia-Hristova** [comment]
Hello @stevenleeza and @spstratis , 

This issue should be fixed so I'll close it.

Have in mind that repository is only for examples.

If you have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thank you in advance!If you have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thank you in advance!
