### ISSUE TITLE
UIScreen.mainScreen is not a function because of IOS 10

### ISSUE THREAD

**Issue by ignaciolarranaga** [telerik/nativescript-ui-samples#126]
### Tell us about the problem

The signature of the method changes on the last release
### Which platform(s) does your issue occur on?

IOS
### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it): `2.3.0`
- Cross-platform modules: (check the 'version' attribute in the
  `node_modules/tns-core-modules/package.json` file in your project): `"tns-core-modules": "^2.3.0",`
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
  `package.json` file of your project)

```
"tns-ios": {
      "version": "2.3.0"
}
```
### Please tell us how to recreate the issue in as much detail as possible.

It is just enough to update to the latest and try.

Sep 17 06:44:01 MacBook-Pro-de-Ignacio gyntoclient[61193]: CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:342:26: Unhandled Promise rejection: Error in /Users/ignacio/Library/Developer/CoreSimulator/Devices/00A4117D-42D7-4D34-A741-4D4FAA4286CD/data/Containers/Bundle/Application/3CCEEC89-90F3-425E-BC14-7C4EAB5E6306/gyntoclient.app/app/pages/user/user.html:9:0 caused by: UIScreen.mainScreen is not a function. (**In 'UIScreen.mainScreen()', 'UIScreen.mainScreen'** is an instance of UIScreen) ; Zone: angular ; Task: Promise.then ; Value: Error: Error in /Users/ignacio/Library/Developer/CoreSimulator/Devices/00A4117D-42D7-4D34-A741-4D4FAA4286CD/data/Containers/Bundle/Application/3CCEEC89-90F3-425E-BC14-7C4EAB5E6306/gyntoclient.app/app/pages/user/user.html:9:0 caused by: UIScreen.mainScreen is not a function. (In 'UIScreen.mainScreen()', 'UIScreen.mainScreen' is an instance of UIScreen) RadSideDrawer@file:///app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js:13:87

**Comment by zf8848** [comment]
nativescript-telerik-ui-pro 1.4.0 have the same problem iOS 10

**Comment by dwaan** [comment]
I have the same problem:
tns version: 2.3.0
tns-ios version: 2.3.0

After I update to the latest Xcode, seems like I can't use nativescript-telerik-ui anymore. If I remove it from my xml, it's working fine.

The problem seems like the sidebar module is not found.
```
Sep 19 09:46:34 themilkyway HiStyle[23301]: file:///app/tns_modules/ui/builder/builder.js:162:56: JS ERROR Error: Building UI from XML. @file:///app/listing.xml:23:3
	 ↳Module '/Users/dwan/Library/Developer/CoreSimulator/Devices/3090D8E5-BCD6-4BA9-A040-FA8E3F6B9457/data/Containers/Bundle/Application/465FD1A7-1441-4886-BB83-85DADC588C6F/HiStyle.app/app/nativescript-telerik-ui/sidedrawer' not found for element 'nativescript-telerik-ui/sidedrawer:RadSideDrawer'.
	   ↳Could not find module '/Users/dwan/Library/Developer/CoreSimulator/Devices/3090D8E5-BCD6-4BA9-A040-FA8E3F6B9457/data/Containers/Bundle/Application/465FD1A7-1441-4886-BB83-85DADC588C6F/HiStyle.app/app/nativescript-telerik-ui/sidedrawer'. Computed path '/Users/dwan/Library/Developer/CoreSimulator/Devices/3090D8E5-BCD6-4BA9-A040-FA8E3F6B9457/data/Containers/Bundle/Application/465FD1A7-1441-4886-BB83-85DADC588C6F/HiStyle.app/app/nativescript-telerik-ui/sidedrawer'.
Sep 19 09:46:34 themilkyway com.apple.CoreSimulator.SimDevice.3090D8E5-BCD6-4BA9-A040-FA8E3F6B9457.launchd_sim[16144] (UIKitApplication:id.sagara.histyle[0xd9e4][23301]): Service exited due to Segmentation fault: 11
```

I try the SDK example from nativescript-telerik-ui and it's broken also.

**Comment by moreaup** [comment]
Same problem here :/

**Comment by ginev** [comment]
Hi guys,

As it seems Apple have updated the API (https://developer.apple.com/reference/uikit/uiscreen/2097556-mainscreen?language=objc) and `mainScreen` is now a property. We're going to update the NS UI plugin addressing this API change.

**Comment by skarlatov** [comment]
Thanks for reporting this. The issue has been fixed in our development branch. We will update the released package shortly.

**Comment by moreaup** [comment]
Do you have an idea when the release will be update ?

**Comment by ginev** [comment]
@moreaup you should be able to download a fixed version now.

**Comment by moreaup** [comment]
Thanks,

But their is still another problem.
I already reported this issue on the forum, about a month ago. It was fixed but today i'm experiencing the same problem. Possible regression?
http://www.telerik.com/forums/radlistview-inside-radsidedrawer-problem

But that's something else, I will post another issue.

**Comment by sdelussu** [comment]
I have an identical problem with nativescript-telerik-ui-pro 1.4.1 on IOS 10
I got this error : utils.ios.getter(UIScreen, UIScrenn.mainScreen) is not a function when I want to use SideDrawer

Maybe someone can help me ?

**Comment by skarlatov** [comment]
Hi, sdelussu

You can fix this by updating nativescript to a newer version. The new TNS Core modules include this function.

**Comment by sdelussu** [comment]
I'm currently using the 2.2.0 version of NativeScript and I see that the 2.3.0 is experimental.
Can I upgrade to the 2.3.0 ?
