### ISSUE TITLE
How RadListView support Gesture

### ISSUE THREAD

**Issue by ryc16** [telerik/nativescript-ui-samples#127]
Does RadListView support Gesture like pan? For example, I want to detect RadListView scrolling down but can't find any event support it. Try to manually register "pan" but doesn't work.

**Comment by ginev** [comment]
Hello @ryc16 ,

currently there's no API to detect scrolling. Could you please describe in more details the scenario you would like to implement?

Thanks!

**Comment by ryc16** [comment]
@ginev, one simple case, if I want to show a "go to top" button while RadListView scroll down. This is very common and can implement transitional ListView with pan event.  I was trying to use itemLoadingEvent to see if it works similar like pan but it is not exactly. Normally on pan event, it return the "relative" deltaY for every pan but itemLoadingEvent has "absolute" item index.

**Comment by ginev** [comment]
This issue was moved to telerik/nativescript-ui-feedback#118
