### ISSUE TITLE
Tap Event Fires Slow / Doesn't Fire

### ISSUE THREAD

**Issue by SpoonIsBad** [telerik/nativescript-ui-samples#13]
I've wired up my menu items to a  tap event to actually navigate to a  new page. Although, it feels like the tap event doesn't always fire, or is extremely slow to fire. Any suggestions?

inside my main-view-model.js

var frameModule = require("ui/frame");

inside of the MainViewModel method()
MainViewModel.prototype.menuTap= function () {
		var topmost = frameModule.topmost();
		var navigationEntry = {
			moduleName: "home",
			animated: true
		};
		
		topmost.navigate(navigationEntry);
	}

I just have it hard coded to home for now until I could get it working more consistently.

I'll post all of  XML if you'd like to see but it's what you'd imagine:
<Label margin="10" padding="20" text="Home" id="Home" tap="{{ homeTap }}"/>

**Comment by SpoonIsBad** [comment]
I removed the app from the device, and reinstalled and everything seems to be working alright. Sorry for the false issue.

**Comment by mayureshjadhav** [comment]
Hey @SpoonIsBad , I don't think it's false issue. I tried the method you mentioned above but still not working properly.
