### ISSUE TITLE
'scrollToIndex()' does not work with 'Horizontal' RadListView on iOS

### ISSUE THREAD

**Issue by Daxito** [telerik/nativescript-ui-samples#131]
Using NS UI Version 1.4.1, The ScrollToIndex() does not work for horizontal listview,
please check the attached demo, just run it and it should scroll to index 8 but it does not.

Now, if you change the orientation to Vertical, then it scrolls.

[listviewsample.zip](https://github.com/telerik/nativescript-ui-samples/files/490679/listviewsample.zip)

**Comment by Daxito** [comment]
I notices that this works for Android only, Android scroll to index works, ios does not when list view is horizontal.

**Comment by ginev** [comment]
@Daxito, thanks for the feedback. We will investigate and eventually schedule for fixing.

**Comment by VladimirAmiorkov** [comment]
Hi @Daxito ,

I managed to reproduce the issue on the iOS platform, the Android counterpart works as expected. I have edited the title to better described the scenario and environment. 

For future issues report please provide full information as shown in the "github issue template", it really help us pinpoint the scenario, environment and versions.
