### ISSUE TITLE
sdkAngular has stopped

### ISSUE THREAD

**Issue by kuncevic** [telerik/nativescript-ui-samples#137]
I am running `tns run android --emulator`
Then when app gets deployed to the emulator all I can see is popup with an error saying
`sdkAngular has stopped` as per image

![image](https://cloud.githubusercontent.com/assets/1283734/19717079/afa5d1dc-9baa-11e6-9167-297856539a05.png)
I am running Windows 10

That is my AVD details:

![image](https://cloud.githubusercontent.com/assets/1283734/19717182/1cb5bf3a-9bab-11e6-8ccc-9e0863a9f67b.png)

However I am able to run another codesamples just fine e.g https://github.com/NativeScript/sample-Groceries

**Comment by Natalia-Hristova** [comment]
Hello @kuncevic ,

I tried it with the latest [sdkAngular](https://github.com/telerik/nativescript-ui-samples-angular)  and their package.json
```
{
  "name": "nativescript-telerik-ui-sdk-angular-examples",
  "version": "1.6.1",
  "description": "Nativescript project that shows the NativeScript UI with Angular2",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": {
    "type": "git",
    "url": "git@github.com/telerik/nativescript-ui-samples-angular.git"
  },
  "nativescript": {
    "id": "org.nativescript.sdkAngular",
    "tns-android": {
      "version": "2.5.0"
    },
    "tns-ios": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/common": "~2.4.3",
    "@angular/compiler": "~2.4.3",
    "@angular/core": "~2.4.3",
    "@angular/forms": "~2.4.3",
    "@angular/http": "~2.4.3",
    "@angular/platform-browser": "~2.4.3",
    "@angular/platform-browser-dynamic": "~2.4.3",
    "@angular/router": "~3.4.3",
    "nativescript-angular": "1.4.0",
    "nativescript-fresco": "^1.0.11",
    "nativescript-intl": "^0.0.4",
    "nativescript-telerik-ui-pro": "1.6.1",
    "nativescript-unit-test-runner": "^0.3.2",
    "rxjs": "~5.0.1",
    "tns-core-modules": "2.5.1"
  },
  "devDependencies": {
    "babel-traverse": "6.10.4",
    "babel-types": "6.10.2",
    "babylon": "6.8.1",
    "chai": "^3.5.0",
    "codelyzer": "1.0.0-beta.2",
    "filewalker": "0.1.3",
    "karma": "^0.13.22",
    "karma-chai": "^0.1.0",
    "karma-mocha": "^0.2.2",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "mocha": "^2.4.5",
    "nativescript-dev-android-snapshot": "0.0.6",
    "nativescript-dev-typescript": "^0.3.1",
    "tslint": "^3.14.0",
    "typescript": "2.1.5",
    "zone.js": "^0.6.21"
  }
}

```

and `tns run android --emulator` works.

I'll close this issue because this repository is only for examples.

If you have any other feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thanks in advance!
