### ISSUE TITLE
RadListView not working on iOS

### ISSUE THREAD

**Issue by bm-software** [telerik/nativescript-ui-samples#138]
I've included RadListView to show a contacts list:

    <RadListView id="contactsList" [items]='contacts' selectionBehavior="None" *ngIf="contacts.length > 0"
            (itemTap)="onItemTap($event)"
            (itemHold)="onItemHold($event)"
            itemSwipe="false"
            pullToRefresh="true"
            (pullToRefreshInitiated)="onPullToRefreshInitiated($event)">
            <ListViewLinearLayout tkListViewLayout scrollDirection="Vertical" 
                itemInsertAnimation="Default" itemDeleteAnimation="Default">
            </ListViewLinearLayout>

            <template tkListItemTemplate let-contact='item' >
                <StackLayout height="44">
                    <GridLayout columns="80, *">
                        <Image col="0" [src]="contact.icon" stretch="aspectFill" verticalAlignment="center" horizontalAlignment="center" class="contact-icon"></Image>
                        <StackLayout col="1" verticalAlignment="center" horizontalAlignment="left" color="black" margin="5 0">
                            <Label [text]="contact.name" verticalAlignment="center" horizontalAlignment="left" textWrap="true" id="personalContactName" class="h2"></Label>
                            <Label [text]="contact.phone" verticalAlignment="center" horizontalAlignment="left" class="h3"></Label> 
                            <Label [text]="contact.notes" verticalAlignment="center" horizontalAlignment="left" textWrap="true" class="h3 font-italic"></Label>
                        </StackLayout>
                    </GridLayout>
                    <StackLayout class="hr-light"></StackLayout>
                </StackLayout>
            </template>
            
            <GridLayout *tkListItemSwipeTemplate columns="auto, *, auto" class="listItemSwipeGridLayout">
                <StackLayout id="mark-view" class="markViewStackLayout" col="0" (tap)="onLeftSwipeClick($event)">
                    <Label text="mark" verticalAlignment="center" horizontalAlignment="center"></Label>
                </StackLayout>
                <StackLayout id="delete-view" class="deleteViewStackLayout" col="2" (tap)="onRightSwipeClick($event)">
                    <Label text="delete" verticalAlignment="center" horizontalAlignment="center"></Label>
                </StackLayout>
            </GridLayout>
        </RadListView>
    </StackLayout>

This works fine on Android but not on iOS . Nothing renders and log says:

    Nov  4 15:35:06 Micheles-Mac sosnumbers[9226]: CONSOLE WARN file:///app/tns_modules/nativescript-telerik-ui/listview/listview.js:358:14: The TypeScript constructor "TKListViewDataSourceImpl" will not be executed.
    Nov  4 15:35:06 Micheles-Mac sosnumbers[9226]: CONSOLE WARN file:///app/tns_modules/nativescript-telerik-ui/listview/listview.js:499:14: The TypeScript constructor "ExtendedListViewCell" will not be executed.

How can I solve this?

**Comment by VladimirAmiorkov** [comment]
HI @bm-software ,

Maybe the wrapper layout of the RadListView is an container which is measured correctly to support the RadListView in iOS. Can you share with is the full HTML of both the Component where the RadListView is placed and possibly any nested (page-router-outlet) COmponent's HTML in which those are loaded.

**Comment by bm-software** [comment]
Hi @VladimirAmiorkov , 
Here is the code you asked for.

**app.component.ts**

    @Component({
      selector: "main",
      template: "<page-router-outlet></page-router-outlet>"
    })
    export class AppComponent {
        [...]
    }

Inside `page-router-outlet` tag a TabView is loaded which contains five tabs among which there is the component tabs that contains the RadListView.

**tabs.html**

    <ActionBar [title]="title"> 
        <NavigationButton text="Indietro" icon="res://ic_arrow_back_white_48dp" (tap)="goBack()"></NavigationButton> 
        <ActionItem [text]="'share' | translate" (tap)="share()" android.systemIcon="ic_menu_share_holo_dark" ios.systemIcon="9" ios.position="right"></ActionItem>
    </ActionBar>
    
    <TabView #tabView [(ngModel)]="tabSelectedIndex" (selectedIndexChanged)="onTabChanged(tabView.selectedIndex)" 
        selectedColor="#FFFFFF" tabsBackgroundColor="#F44336"> 
    
        <StackLayout *tabItem="isAndroid ? {iconSource: 'res://ic_warning_white_48dp'} : {iconSource: 'res://ic_warning_white_48dp', title: 'Emergenza'}">
            <ContentView [marginBottom]="navigationBarHeight">
                <emergency></emergency>
            </ContentView >
        </StackLayout>
        
        <StackLayout *tabItem="isAndroid ? {iconSource: 'res://ic_grid_on_white_48dp'} : {iconSource: 'res://ic_grid_on_white_48dp', title: 'Utilità'}">
            <ContentView [marginBottom]="navigationBarHeight">
                <utility></utility>
            </ContentView>
        </StackLayout>
        
        <StackLayout *tabItem="isAndroid ? {iconSource: 'res://ic_bubble_chart_white_48dp'} : {iconSource: 'res://ic_bubble_chart_white_48dp', title: 'Servizi'}">
            <ContentView [marginBottom]="navigationBarHeight">
                <service></service>
            </ContentView>
        </StackLayout>
    
        <StackLayout *tabItem="isAndroid ? {iconSource: 'res://ic_contacts_white_48dp'} : {iconSource: 'res://ic_contacts_white_48dp', title: 'Personali'}">
            <ContentView [marginBottom]="navigationBarHeight">
                <personal></personal>
            </ContentView>
        </StackLayout>
    
        <StackLayout *tabItem="isAndroid ? {iconSource: 'res://ic_my_location_white_48dp'} : {iconSource: 'res://ic_my_location_white_48dp', title: 'Posizione'}">
            <ContentView [marginBottom]="navigationBarHeight">
                <position></position>
            </ContentView>
        </StackLayout>
    </TabView>

In particular:

    <StackLayout *tabItem="isAndroid ? {iconSource: 'res://ic_contacts_white_48dp'} : {iconSource: 'res://ic_contacts_white_48dp', title: 'Personali'}">
        <ContentView [marginBottom]="navigationBarHeight">
            <personal></personal>
        </ContentView>
    </StackLayout>

Finally, the personal component contains the following layout:
**personal.html**

    <GridLayout rows="auto, *">
        <StackLayout row="1">
            <location></location>
            
            <CardView shadowColor="#949494" elevation="10" margin="10">
                <StackLayout orientation="vertical">
                    <Label text="Numeri Personali" verticalAlignment="center" horizontalAlignment="left" textWrap="true" class="card-header"></Label>
                    <StackLayout class="hr-light"></StackLayout>
                    
                    <GridLayout rows="*" *ngIf="contacts.length === 0">
                        <Label row="0" text="Nessun contatto inserito." verticalAlignment="center" horizontalAlignment="center" 
                            textWrap="true" class="h3 font-italic">
                        </Label>
                    </GridLayout>
    
                    <RadListView id="contactsList" [items]='contacts' selectionBehavior="None" *ngIf="contacts.length > 0"
                        (itemTap)="onItemTap($event)"
                        (itemHold)="onItemHold($event)"
                        itemSwipe="false"
                        pullToRefresh="true"
                        (pullToRefreshInitiated)="onPullToRefreshInitiated($event)">
                        <ListViewLinearLayout tkListViewLayout scrollDirection="Vertical" 
                            itemInsertAnimation="Default" itemDeleteAnimation="Default">
                        </ListViewLinearLayout>
    
                        <template tkListItemTemplate let-contact='item' >
                            <StackLayout>
                                <GridLayout columns="80, *">
                                    <Image col="0" [src]="contact.icon" stretch="aspectFill" verticalAlignment="center" horizontalAlignment="center" class="contact-icon"></Image>
                                    <StackLayout col="1" verticalAlignment="center" horizontalAlignment="left" color="black" margin="5 0">
                                        <Label [text]="contact.name" verticalAlignment="center" horizontalAlignment="left" textWrap="true" id="personalContactName" class="h2"></Label>
                                        <Label [text]="contact.phone" verticalAlignment="center" horizontalAlignment="left" class="h3"></Label> 
                                        <Label [text]="contact.notes" verticalAlignment="center" horizontalAlignment="left" textWrap="true" class="h3 font-italic"></Label>
                                    </StackLayout>
                                </GridLayout>
                                <StackLayout class="hr-light"></StackLayout>
                            </StackLayout>
                        </template>
                        
                        <GridLayout *tkListItemSwipeTemplate columns="auto, *, auto" class="listItemSwipeGridLayout">
                            <StackLayout id="mark-view" class="markViewStackLayout" col="0" (tap)="onLeftSwipeClick($event)">
                                <Label text="mark" verticalAlignment="center" horizontalAlignment="center"></Label>
                            </StackLayout>
                            <StackLayout id="delete-view" class="deleteViewStackLayout" col="2" (tap)="onRightSwipeClick($event)">
                                <Label text="delete" verticalAlignment="center" horizontalAlignment="center"></Label>
                            </StackLayout>
                        </GridLayout>
                    </RadListView>
                </StackLayout>
            </CardView>
        </StackLayout>
    
        <Fab row="1" class="fab-button"
            (tap)="showAddContactModal()"
            icon="res://ic_add_white_48dp"
            rippleColor="#f1f1f1"
            verticalAlignment="bottom"
            horizontalAlignment="right"
            hideOnSwipeOfView="contactsList">
        </Fab>
    </GridLayout>

Is there something wrong?

**Comment by VladimirAmiorkov** [comment]
Hi @bm-software ,

I apologize for the late response on this. After testing the provided code snippets it looks that the issue is indeed caused by the structure of the layout in your **personal.html**. 

- First in some scenarios in the different iOS versions declaring the `tkListViewLayout` (in your case ListViewLinearLayout) is best to be declared after the templates ([tkListItemTemplate](url)/
/`tkListItemSwipeTemplate`). This is because of the way the native iOS elements behavior on the different versions.
- In order to resolve the RadListView not showing you should wrap the  RadListView with a container which does not measure itself with infinity, like a `GridLayout`:

```
<GridLayout>
    <RadListView id="contactsList" [items]='contacts' selectionBehavior="None" *ngIf="contacts.length > 0" (itemTap)="onItemTap($event)"
        (itemHold)="onItemHold($event)" itemSwipe="false" pullToRefresh="true" (pullToRefreshInitiated)="onPullToRefreshInitiated($event)">
        <ListViewLinearLayout tkListViewLayout scrollDirection="Vertical" itemInsertAnimation="Default" itemDeleteAnimation="Default">
        </ListViewLinearLayout>

        <template tkListItemTemplate let-contact='item'>
            <StackLayout>
                <GridLayout columns="80, *">
                    <Image col="0" [src]="contact.icon" stretch="aspectFill" verticalAlignment="center" horizontalAlignment="center" class="contact-icon"></Image>
                    <StackLayout col="1" verticalAlignment="center" horizontalAlignment="left" color="black" margin="5 0">
                        <Label [text]="contact.name" verticalAlignment="center" horizontalAlignment="left" textWrap="true" id="personalContactName"
                            class="h2"></Label>
                        <Label [text]="contact.phone" verticalAlignment="center" horizontalAlignment="left" class="h3"></Label>
                        <Label [text]="contact.notes" verticalAlignment="center" horizontalAlignment="left" textWrap="true" class="h3 font-italic"></Label>
                    </StackLayout>
                </GridLayout>
                <StackLayout class="hr-light"></StackLayout>
            </StackLayout>
        </template>

        <GridLayout *tkListItemSwipeTemplate columns="auto, *, auto" class="listItemSwipeGridLayout">
            <StackLayout id="mark-view" class="markViewStackLayout" col="0" (tap)="onLeftSwipeClick($event)">
                <Label text="mark" verticalAlignment="center" horizontalAlignment="center"></Label>
            </StackLayout>
            <StackLayout id="delete-view" class="deleteViewStackLayout" col="2" (tap)="onRightSwipeClick($event)">
                <Label text="delete" verticalAlignment="center" horizontalAlignment="center"></Label>
            </StackLayout>
        </GridLayout>
    </RadListView>
</GridLayout>
```

On a side note, I noticed that there are multiple levels of layouts in your code snippets. As a rule of thumb the more layouts you declared the worst the performance may become. It is good to try to keep as fewer levels (stacking) of layouts in your views as possible.
