### ISSUE TITLE
Nativescript : nativescript-telerik-ui building failed

### ISSUE THREAD

**Issue by azandrew-sidoine** [telerik/nativescript-ui-samples#143]
Hi guys am having a problem with the nativescript-telerik-ui. 

CLI version 2.3.0, nativescript-telerik-ui version: 1.4.0
build failed with the following error:

D:\new_project_folder\my-app\platforms\android\build\intermediates\res\merged\F0F1\debug\values-v23\values-v23.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.

D:\new_project_folder\my-app\platforms\android\build\intermediates\res\merged\F0F1\debug\values-v23\values-v23.xml:18: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

:processF0F1DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1DebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\ANONYM\AppData\Local\Android\sdk\build-tools\24.0.3\aapt.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4 mins 26.436 secs
Command D:\new_project_folder\my-app\platforms\android\gradlew.bat failed with exit code 1
# build android

**Comment by Natalia-Hristova** [comment]
Hello @azandrew-sidoine , 

I'll close this issue because this repository is only for examples. 
You can try our latest version of the plugin. If this still happens or you just have any other feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thank you in advance!
