### ISSUE TITLE
ld: file too small (length=0) file '../TelerikUI.framework/TelerikUI' for architecture i386

### ISSUE THREAD

**Issue by NikJaySix** [telerik/nativescript-ui-samples#144]
### Tell us about the problem
I just installed the nativescript ui pro plugin (downloaded package from telerik after purchasing) and i can no longer build my project. i receive this error:

> ld: file too small (length=0) file '/Users/nik/Sites/nativescript/I-Forgot-Milk/lib/iOS/TelerikUI.framework/TelerikUI' for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please see attached the build log 
[build-ios-log.txt](https://github.com/telerik/nativescript-ui-samples/files/603275/build-ios-log.txt)

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.40
- Cross-platform modules: 2.4.0
- Runtime(s): "tns-ios" 2.4.0
- Plugin(s): 

"dependencies": {
    "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/http": "2.1.2",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "@angular/router": "3.1.2",
    "email-validator": "^1.0.7",
    "nativescript-angular": "1.1.3",
    "nativescript-background-fetch": "^1.0.2",
    "nativescript-background-geolocation-lt": "^1.2.5",
    "nativescript-geolocation": "0.0.15",
    "nativescript-plugin-firebase": "^3.8.2",
    "nativescript-telerik-ui-pro": "file:../nativescript-ui-pro.tgz",
    "nativescript-theme-core": "^0.2.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "2.4.0"
  },
  "devDependencies": {
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^2.0.10",
    "zone.js": "~0.6.21"
  }
### Please tell us how to recreate the issue in as much detail as possible.

Install nativescript ui pro

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Thank You!

**Comment by NikJaySix** [comment]
i just fixed this issue myself by copying over the TelerikUI file from the downloaded files into the lib/ios/TelerikUi.framework folder.. but just curious whether this file should have been empty when i installed the plugin? can i avoid this in the future and ensure a successful installation?

thanks!

**Comment by Natalia-Hristova** [comment]
Hello @NikJaySix,

First , sorry for the late reply. 

Nice to hear that you found workaround! Indeed, you should not do any extra work (copy something and paste it somewhere) to use the plugin. If you still face it, feel free to log your feedback, issues or feature requests  in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Please have in mind that all issues here will be moved (if they are still valid) and closed because this repository is only for examples. 

Thank you in advance!
