### ISSUE TITLE
Only iOS 8+?

### ISSUE THREAD

**Issue by emiloberg** [telerik/nativescript-ui-samples#15]
Are the components only supported in iOS 8+ ?

Took me a while to figure out, but when I tried to start the sample app on a iOS7 device it kept on crashing. Is this as intended?

**Comment by ginev** [comment]
Hi @emiloberg,

Yes, the components are supported only on iOS 8+ because the Telerik UI for iOS suite (on which Telerik UI for NS depends) is an embedded framework which only works on iOS 8+.

We will update our documentation with information about this right away.

Thanks!

**Comment by ligaz** [comment]
Will this requirement be relax to iOS 7 once CLI supports static libs in plugins?

**Comment by karaahmed** [comment]
Yes, then we will rely on TelerikUI for iOS that is distributed as fat static library.

**Comment by danicomas** [comment]
@ginev @ligaz Which is the roadmap about support on iOS 7?

**Comment by manijak** [comment]
@ginev @ligaz Any updates on this project? What's new i 1.3.0?

Would be nice if the paid and free components were separated. 

Support for iOS 7?

**Comment by alexrainman** [comment]
+1 to separate SideDrawer from paid library.

**Comment by alexrainman** [comment]
iOS 7 is only 10% of market share.
