### ISSUE TITLE
Error while deploying to iTunesConnect

### ISSUE THREAD

**Issue by dpdragnev** [telerik/nativescript-ui-samples#150]
Hello,

I am trying to upload my project to the AppStore via iTunesConnect.  I am using AppBuilder and NS version 2.3.  I am getting the following error after the upload:

This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data. 

Any ideas on how to solve this?

Thank you

**Comment by bradmartin** [comment]
Ran into this also two weeks ago and took me forever to figure out the UI suite has the calendar key in the plist. I had to set a value for it in xcode, new archive and finally got it uploaded. I don't have any suggestions on best approach to fix but something to help others would be nice because it's a time killer and frustrating 😄

**Comment by VladimirAmiorkov** [comment]
Hi guys,

You can take a look at [this forum post](http://www.telerik.com/forums/2016-3-914-3-nscalendarsusagedescription-nsphotolibraryusagedescription-required-when-deploying-to-testflight) that goes in greater details why the above issue has started occurring.

In short here is the main points from the forum post:

> Since iOS 10 Apple requires to provide reasoning whenever you are using sensitive data in which RadCalendar is included.
> Nativescript UI provides an easy way for the RadCalendar to get synchronized with the device's calendar and that specific action is though of as information sensitive. Unfortunately we weren't able to find a way to resolve the issue globally, for example,  by adding the NSCalendarsUsageDescription variable to the info.plist of the native framework which is used in the nativescript-telerik-ui plugin. Our recommendation for now is to put the property in your info.plist. Since you are not using the TKCalendar component in any way, your users will not be prompted with this permission.
