### ISSUE TITLE
RadListView does not renders the list properly with angular 2 (2.2.1)

### ISSUE THREAD

**Issue by manishmlv50** [telerik/nativescript-ui-samples#152]
## Please, provide the details below:

RadListView does not renders the list properly with angular 2 (2.2.1) but renders the same properly with angular 2 version (2.1.2)

I have the following package 

"dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/router": "3.2.1",
    "nativescript-angular": "next",
    "email-validator": "^1.0.4",
    "moment": "^2.17.0",
    "nativescript-cardview": "1.2.0",
    "nativescript-carousel": "^2.1.1",
    "nativescript-checkbox": "1.2.2",
    "nativescript-drop-down": "1.4.0",
    "nativescript-imagepicker": "2.4.1",
    "nativescript-toast": "1.4.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "^2.4.3",
    "tns-platform-declarations": "^2.4.3"

The listview is not render properly on Android. I haven't tested it on iOS.

**Comment by VladimirAmiorkov** [comment]
Hi @manishmlv50 ,

I just ran the sdkAngular examples with the following versions, without any issues:

```
"dependencies": {
    "@angular/common": "2.4.1",
    "@angular/compiler": "2.4.1",
    "@angular/core": "2.4.1",
    "@angular/forms": "2.4.1",
    "@angular/http": "2.4.1",
    "@angular/platform-browser": "2.4.1",
    "@angular/platform-browser-dynamic": "2.4.1",
    "@angular/router": "3.2.4",
    "rxjs": "5.0.0-beta.12",
    "url": "0.10.3",
    "tns-core-modules": "2.4.4",
    "nativescript-angular": "1.2.0",
    "nativescript-fresco": "^1.0.11",
    "nativescript-intl": "^0.0.4",
    "nativescript-telerik-ui-pro": "1.5.1",
    "nativescript-unit-test-runner": "^0.3.2"
  },
```

Could you see if the 2.4.1 version is working on your end, also if not can you give us more information regarding the observed issue, you mentioned that the RadListView does not render properly, in what way it is not rendered. Is it misbehaving, throwing errors or something else.
