### ISSUE TITLE
SideDrawer error

### ISSUE THREAD

**Issue by dpdragnev** [telerik/nativescript-ui-samples#153]
Hello,

I tried to add the drawer to my existing app and now I am getting the following error:

**Module '/Users/mac/Library/Developer/CoreSimulator/Devices/80686D31-85AC-4B0F-BB26-0D89CCB8CAB3/data/Containers/Bundle/Application/06012A25-C6ED-489A-949C-EAF2CE3F4B6A/cpm.app/app/nativescript-telerik-ui/sidedrawer' not found for element 'nativescript-telerik-ui/sidedrawer:RadSideDrawer'.**

Here is my package.json: (some data is removed for brevity)

```
{
  "name": "cpm",
  "version": "1.0.0",
  "description": "description",
  "license": "license",
  "readme": "readme",
  "repository": "<removed>",
  "nativescript": {
    "id": "com.company.cpm",
    "tns-android": {
      "version": "2.4.1"
    },
    "tns-ios": {
      "version": "2.4.0"
    }
  },
  "dependencies": {
    "nativescript-loading-indicator": "^2.2.2",
    "nativescript-theme-core": "^0.2.1",
    "tns-core-modules": "2.4.3"
  },
  "devDependencies": {
    "babel-traverse": "6.21.0",
    "babel-types": "6.21.0",
    "babylon": "6.14.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*"
  }
}
```

here is my xml:

`
<Page xmlns="http://www.nativescript.org/tns.xsd" xmlns:tsd="nativescript-telerik-ui/sidedrawer" loaded="onLoaded">

    <tsd:RadSideDrawer>
        <tsd:RadSideDrawer.mainContent>

            <StackLayout>
                <Label text="Hello Daniel" textWrap="true" />
                
            </StackLayout>
        

        </tsd:RadSideDrawer.mainContent>
        <tsd:RadSideDrawer.drawerContent>
            <StackLayout>
                <Label text="test" textWrap="true" />
                
            </StackLayout>
        </tsd:RadSideDrawer.drawerContent>
    </tsd:RadSideDrawer>
</Page>
`

Any help is greatly appreciated.
Thank you.

**Comment by VladimirAmiorkov** [comment]
Hi @dpdragnev ,

By the looks of the provided package.json `dependencies` you are missing the nativescript-telerik-ui plugin, which is why you are getting the error: 

> nativescript-telerik-ui/sidedrawer' not found for element 

Simply install the plugin by doing:

> $ tns plugin add nativescript-telerik-ui
