### ISSUE TITLE
nativescript-ui-samples-release\nativescript-ui-s amples-release\sdk\platforms\android\gradlew.bat failed with exit code 1

### ISSUE THREAD

**Issue by vulvaji** [telerik/nativescript-ui-samples#154]
### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

As per given instructions i have executed following commands,

Steps to run the sample:

    cd sdk
    tns run android or tns emulate ios
but not able to run the application. always shows "gradlew.bat failed with exit code 1"

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) :- 2.4.0
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) :- for both ios and android 2.4.0
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.

As per given instructions i have executed following commands,

Steps to run the sample:

    cd sdk
    tns run android or tns emulate ios
but not able to run the application. always shows "gradlew.bat failed with exit code 1"

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

:mergeF0F1F2DebugResources
C:\Root\Dev\Mobile Dev\nativescript-ui-samples-release\nativescript-ui-samples-r
elease\sdk\platforms\android\build\intermediates\exploded-aar\com.android.suppor
t\appcompat-v7\25.1.0\res\drawable-hdpi-v4\abc_textfield_search_default_mtrl_alp
ha.9.png: Error: File path too long on Windows, keep below 240 characters : C:\R
oot\Dev\Mobile Dev\nativescript-ui-samples-release\nativescript-ui-samples-relea
se\sdk\platforms\android\build\intermediates\exploded-aar\com.android.support\ap
pcompat-v7\25.1.0\res\drawable-hdpi-v4\abc_textfield_search_default_mtrl_alpha.9
.png
:mergeF0F1F2DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeF0F1F2DebugResources'.
> C:\Root\Dev\Mobile Dev\nativescript-ui-samples-release\nativescript-ui-samples
-release\sdk\platforms\android\build\intermediates\exploded-aar\com.android.supp
ort\appcompat-v7\25.1.0\res\drawable-hdpi-v4\abc_textfield_search_default_mtrl_a
lpha.9.png: Error: File path too long on Windows, keep below 240 characters : C:
\Root\Dev\Mobile Dev\nativescript-ui-samples-release\nativescript-ui-samples-rel
ease\sdk\platforms\android\build\intermediates\exploded-aar\com.android.support\
appcompat-v7\25.1.0\res\drawable-hdpi-v4\abc_textfield_search_default_mtrl_alpha
.9.png

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 1 mins 16.747 secs
Command C:\Root\Dev\Mobile Dev\nativescript-ui-samples-release\nativescript-ui-s
amples-release\sdk\platforms\android\gradlew.bat failed with exit code 1
# run android

**Comment by vulvaji** [comment]
After chaning the version 2.3 to 2.4 in package.json getting following error.


C:\Root\nativescript-ui-samples-release\sdk\platforms\android\build\intermediate
s\res\merged\F0F1F2\debug\values\values.xml:198: AAPT: Attribute "showTitle" has
 already been defined

:processF0F1F2DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1F2DebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.E
xecException: Process 'command 'C:\Users\v140068\AppData\Local\Android\sdk\build
-tools\23.0.3\aapt.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 4 mins 2.744 secs
Command C:\Root\nativescript-ui-samples-release\sdk\platforms\android\gradlew.ba
t failed with exit code 1
# run android

**Comment by VladimirAmiorkov** [comment]
HI @vulvaji ,

I tried to reproduce the described issues but to no avail with both running the latest 2.4.2 version of NativeScript and the 2.4.0.

Can you try to:

- Clean the project but deleting the lib, node_modules and platforms folders
- Upgrade to NativeScript 2.4.2 but doing `$ npm install -g nativescript`

**Comment by vulvaji** [comment]
Tried both ways no luck @VladimirAmiorkov. getting below error.

C:\Root\nativescript-ui-samples-release\sdk\platforms\android\build\intermediate
s\res\merged\F0F1F2\debug\values\values.xml:198: AAPT: Attribute "showTitle" has
 already been defined

:processF0F1F2DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1F2DebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.E
xecException: Process 'command 'C:\Users\Ds\AppData\Local\Android\sdk\build
-tools\23.0.3\aapt.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

**Comment by VladimirAmiorkov** [comment]
@vulvaji can you share a runnable project or at least the code snippets required to reproduce this issue on our end? From the error message it looks like there is some issue with the 'values.xml' of the {N} project, have you made any customizations to the sdk repo's project or are you directly running it after a git clone?

**Comment by vulvaji** [comment]
Yes, i have just cloned it. Regarding code, is it fine if i share 'values.xml' or you need entire project.?

**Comment by VladimirAmiorkov** [comment]
@vulvaji If you can point me to the file directly in our github repo there is not need to upload it yourself, but if you prefer you can send me the entire project so I could get on it as soon as possible.

**Comment by vulvaji** [comment]
you can fine the file here... nativescript-ui-samples-release\sdk\platforms\android\build\intermediate
s\res\merged\F0F1F2\debug\values\values.xml 

issue is : Attribute "showTitle" has already been defined

**Comment by VladimirAmiorkov** [comment]
Hi @vulvaji ,

Thank you for providing this information, unfortunately I am still not able to reproduce this issue on my side. Can you try to reproduce it with our "next" version which is the not officially release version of NativeScript and let us know the same behavior is observed there. From the looks of this issue it looks like there is a mismatch between the tns-core-modules and the NativeScript Android runtime.

If it is not too much trouble here is how you can test our latest (not yet released version of NS):

- Open the "package.json" of the sdk project
- Changed the value of "tns-core-modules" to "next"

`"tns-core-modules": "next"`

- Open a termina/console and do `$ npm install -g nativescript@next`, Skip the install script, as you should have already ran it the first time you installed NativeScript

After that simply open the root of the sdk application and do `$ tns run android` or `$ tns emulate android`

**Comment by will-l-h** [comment]
Was running into the same issue and found the solution [here](https://github.com/NativeScript/android-runtime/issues/680#issuecomment-271842968).  Use Android SDK Manager to install Android SDK Build-tools 25.0.2
