### ISSUE TITLE
Getting these warnings when using RadListView

### ISSUE THREAD

**Issue by NordlingArt** [telerik/nativescript-ui-samples#158]
**Platform:** iOS
**TNS:** 2.4.0

`CONSOLE WARN file:///app/tns_modules/nativescript-telerik-ui/listview/listview.js:382:14: The TypeScript constructor "TKListViewDataSourceImpl" will not be executed.`
`CONSOLE WARN file:///app/tns_modules/nativescript-telerik-ui/listview/listview.js:524:14: The TypeScript constructor "ExtendedListViewCell" will not be executed.`

The RadListView still works as expected but why are they there in the first place?

**Comment by Natalia-Hristova** [comment]
Hello @NordlingArt , 

Thanks for your feedback. You are right! I was able to reproduce it with **2.4.0** and nativescript-telerik-ui-pro **1.4.1**. In the newest version of **{N} 2.5.2** and ** nativescript-telerik-ui-pro 1.6.1** these warnings are not shown anymore. Unfortunately, honestly.. there are new ones.

Good question. And yes, these should not be shown and I believe the team will do its best to fix them.

Now I'll close the issue and will kindly ask you if you have any feedback, questions and issues to log them in our dedicated GitHub repository for NativeScript UI issues https://github.com/telerik/nativescript-ui-feedback/issues.

Thanks in advance.
