### ISSUE TITLE
Is possible to change drawer:SideDrawer.mainContent dinamically?

### ISSUE THREAD

**Issue by danicomas** [telerik/nativescript-ui-samples#16]

**Comment by ginev** [comment]
Hi @danicomas,

Yes, you can do that by simply setting the mainContent property to a new View.

**Comment by danicomas** [comment]
Nice @ginev. The mainContent accept an URL or an instance with builder.load? I am trying to do something like this: https://github.com/NativeScript/NativeScript/issues/703

**Comment by ginev** [comment]
@danicomas, you simply set the mainContent property to an element that inherits from the View module. That could be a Button or a StackLayout containing other elements. In your particular case thins should look something like this:

```JavaScript
    var v = view.getViewById(page, "kk");
    sideDrawer.mainContent = v;
```

**Comment by danicomas** [comment]
@ginev my example would be add an external view (other file) dinamically. Do you know how can I do this?

**Comment by danicomas** [comment]
It works this:
```js
import viewModel = require("./drawer-transitions-model");
import frame = require("ui/frame");
import view = require("ui/core/view");
import layout = require("ui/layouts/stack-layout");
import button = require("ui/button");

export function onPageLoaded(args){
    var page = args.object;
    page.bindingContext = new viewModel.DrawerTransitionsModel();

    if (frame.topmost().ios){
        frame.topmost().ios.controller.interactivePopGestureRecognizer.enabled = false;
    }
    
    var btn4 = new button.Button();
    btn4.text = "kk";
    
    var stackLayout = new layout.StackLayout();
    stackLayout.addChild(btn4); 
    
    var v = view.getViewById(page, "sideDrawer");
    v.mainContent = stackLayout;
}
```

**Comment by danicomas** [comment]
But with external StackLayout I haven't found the way.

**Comment by ginev** [comment]
@danicomas, can you please paste the code you are using to dynamically load the StackLayout from an XML file? I will need the XML source, as well as the JavaScript you are using. Theoretically, your approach should be working as expected.

**Comment by danicomas** [comment]
Here the code @ginev

sdk/app/sidedrawer/transitions/kk.xml
```xml
<StackLayout id="stack">
	<Button tap="buttonTap" text="kk" />
</StackLayout>
```

sdk/app/sidedrawer/transitions/kk.ts
```js
export function onPageLoaded(args){
    var page = args.object;
}
```

sdk/app/sidedrawer/transitions/drawer-transitions.ts
```js
...
export function onPageLoaded(args){
var page = args.object;
page.bindingContext = new viewModel.DrawerTransitionsModel();
var myComponentInstance = builder.load({
            path: "~/sidedrawer/transitions/kk",
            name: "kk"
    });
    
    var x = view.getViewById(myComponentInstance, "stack");
    
    var v = view.getViewById(page, "sideDrawer");
    v.mainContent = x;
}
```

I have tried this too:

```js
...
export function onPageLoaded(args){
var page = args.object;
page.bindingContext = new viewModel.DrawerTransitionsModel();
var myComponentInstance = builder.load({
            path: "~/sidedrawer/transitions/kk",
            name: "kk"
    });
    
    var v = view.getViewById(page, "sideDrawer");
    v.mainContent = myComponentInstance;
}
```

**Comment by ginev** [comment]
Hi @danicomas ,

The following code works as expected on my side:

```JavaScript
function pageLoaded(args) {
    console.log("PAGE LOADED " + args);
    var page = args.object;

    page.bindingContext = new vmModule.MainViewModel();

    var myComponentInstance = builder.parse({
            path: "stack-layout.xml",
            name: "kk"
    });
    var sideDrawer = frameModule.topmost().currentPage.getViewById("sideDrawer");
   sideDrawer.mainContent = myComponentInstance;
}
```

Can you check it out and let me know if it does the job?

**Comment by ginev** [comment]
@danicomas,

A quick follow-up.

The code above is wrong. I am not using builder as expected and some specifics of my project fooled me to believe that it works. Take a look at the following snippet:

```
function pageLoaded(args) {
    console.log("PAGE LOADED " + args);
    var page = args.object;

    var myComponentInstance = builder.load({
       path: "~/",
       name: "stack-layout"
   });
    var sideDrawer = page.getViewById("sideDrawer");
    console.log("view: " + myComponentInstance);
   sideDrawer.mainContent = myComponentInstance;
}
```

This code works as expected provided that you have a stack-layout.xml file at root level.

Hope this helps.

**Comment by danicomas** [comment]
Solved. It was a problem about the path. See this: https://github.com/NativeScript/NativeScript/issues/703 Thanks @ginev

**Comment by tannt275** [comment]
I have to custom xml name: MyControl as: 
<StackLayout id="mycontrolLayout">
  <Label id="Label1" text="mymodulewithxml" />
  <Button text="Click!" tap="buttonTap" id="buttonWidget" />
</StackLayout>
and mainlayout as:
<Page xmlns="http://www.nativescript.org/tns.xsd"
      loaded ="pageLoaded">
  <StackLayout id="stackLayout">
    <Label text="Hello Widgets"/>
  </StackLayout>
</Page>
In My mainpage is:
var view = require("ui/core/view");
function pageLoaded(args) {
    var page = args.object;
      var mainLayout = view.getViewById(page,"stackLayout");
      var builder = require("ui/builder");
    var myComponentInstance = builder.load({
        path: "~/xml-decleration",
        name: "MyControl"
    });
    mainLayout.addChild(myComponentInstance);

 }
exports.pageLoaded = pageLoaded;
How i can find id of button was defined in MyControl.xml

**Comment by emmanuel128** [comment]
@tannt275 Does `tap="buttonTap"` works fine on your code?

@ginev @danicomas  I'm trying to change the drawer content but the tap events doesn't work. Any idea?
