### ISSUE TITLE
Does not work with webpack

### ISSUE THREAD

**Issue by ignaciolarranaga** [telerik/nativescript-ui-samples#161]
### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.2
- Cross-platform modules: 2.4.4
- Runtime(s): ios 2.4.0 / android: 2.4.1

### Please tell us how to recreate the issue in as much detail as possible.
If you add the plugin and try to start with webpack (npm run start-ios-bundle) you will get the error.

Here is the stack trace:
```
ERROR in Unexpected value 'LISTVIEW_DIRECTIVES' declared by the module 'MainModule'

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in '/Users/ignacio/Workspaces/DuenoVende/hezea-app/app'
 @ ./main.aot.ts 2:0-60

ERROR in ../~/nativescript-angular/router/ns-module-factory-loader.js
Module not found: TypeError: Cannot convert undefined or null to object
 @ ../~/nativescript-angular/router/ns-module-factory-loader.js 23:15-40
 @ ../~/nativescript-angular/router.js
 @ ./vendor.ts

ERROR in ../~/nativescript-angular/router/ns-module-factory-loader.js
Module not found: TypeError: Cannot convert undefined or null to object
 @ ../~/nativescript-angular/router/ns-module-factory-loader.js 29:27-46
 @ ../~/nativescript-angular/router.js
 @ ./vendor.ts
```

I think it is the same as here: https://github.com/NativeScript/nativescript-fresco/issues/28 (i.e. it is not prepared for AOT).

**Comment by patrickpereira** [comment]
+1

**Comment by tomvardasca** [comment]
+1

**Comment by dunqan** [comment]
+1

**Comment by codeback** [comment]
Yes please, we need it too.

**Comment by DevCappe** [comment]
+1

**Comment by pluservice** [comment]
+1

**Comment by mcler** [comment]
+1

**Comment by julietacampos** [comment]
+1

**Comment by ginev** [comment]
Hi all,

We need to address some issues in the Chart component before releasing AoT support so stay tuned. Please refer to this issue regarding this topic from now on: https://github.com/telerik/nativescript-ui-feedback/issues/108
