### ISSUE TITLE
Build error from nativescript-telerik-ui-pro after upgrading Nativescript

### ISSUE THREAD

**Issue by markfarl** [telerik/nativescript-ui-samples#162]
I upgraded my project to NS 2.4.2 from 2.3~  And now when I build on Android I get this error

:processF0F1F2F3F4DebugResources 
\platforms\android\build\intermediates\res\merged\F0F1F2F3F4\debug\values\values.xml:193: AAPT: Attribute "showTitle" has already been defined

I know it is nativescript-telerik-ui-pro as it disappears when I remove from package.json, and doing file search the only reference to 'showTitle' is in Calender

**Comment by will-l-h** [comment]
This looks very similar to this [another issue](https://github.com/telerik/nativescript-ui-samples/issues/154) in this repo.  

Here's the [solution](https://github.com/NativeScript/android-runtime/issues/680#issuecomment-271842968).  Use Android SDK Manager to install Android SDK Build-tools 25.0.2

**Comment by markfarl** [comment]
Funnily enough I actually was using SDK Build-tools 25 when I first encountered the issue. I had updated both NS and SDK simultaneously, and after which downgraded SDK and it still appeared. I have reverted Nativescript back to 2.3 to resolve, maybe I'll try 2.4.0

**Comment by Daxito** [comment]
One of my coworkers is still having this issue, NS 2.4.2 and his SDK Screen List looks exactly like mine that works and still gets this error. I was thinking that maybe he should uninstall ALL android related SDKs, FULL Android MAC Cleaning and then reinstall everything back in again and see what happens.

**Comment by ginev** [comment]
@Daxito what about installing the 25.0.2 build tools? Doesn't that help?

**Comment by Daxito** [comment]
@ginev 
Seems like after running this command we got from [http://docs.nativescript.org/start/quick-setup](url) worked

ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"

Thanks!
