### ISSUE TITLE
RadListView: Scroll lost on Android navigation

### ISSUE THREAD

**Issue by ignaciolarranaga** [telerik/nativescript-ui-samples#165]
### Tell us about the problem
If you navigate to a page and go back on Android you lost the current scroll on your navigation (i.e. you return to the top of the list instead of your scrolled position).
On iOS it does work properly but not on Android.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.2
- Cross-platform modules: 2.4.4
- Runtime(s): (look for the 2.4.0
- Plugin(s): "nativescript-telerik-ui": "next" (because already handling unpublished fixes),

### Please tell us how to recreate the issue in as much detail as possible.
Easy, just do it and will see it.

**Comment by Natalia-Hristova** [comment]
Hello @ignaciolarranaga, 

This issue is known, reported and will be fixed. I'll move it in our dedicated GitHub repository for NativeScript UI issues https://github.com/telerik/nativescript-ui-feedback/issues and close it here (this repository contains examples only).
Thanks for your feedback.
