### ISSUE TITLE
Can't find variable: TKListViewDelegate

### ISSUE THREAD

**Issue by MalinGunasekara** [telerik/nativescript-ui-samples#167]
### I was getting Can't find variable: TKListViewDelegate, Only on iOS
I have done 95% of the project for now in iOS suddenly while I was running the app on simulator it gives me this error , It worked properly before ( In both Android and iOS ). Even now It works perfectly on Android.

1   0x102feb33c -[TNSRuntime executeModule:referredBy:]
2   0x101980489 main
3   0x106eb368d start
file:///app/tns_modules/nativescript-telerik-ui-pro/listview/listview.js:376:63: JS ERROR ReferenceError: Can't find variable: TKListViewDelegate
  Feb  1 17:29:48 malins-imac com.apple.CoreSimulator.SimDevice.EF68AFE9-7774-4919-8B28-2D522846A22F.launchd_sim[3326] (UIKitApplication:com.J##W.L#####y[0xca1][8540]): Service exited due to Segmentation fault: 1

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.4.2
- Cross-platform modules: 2.5.0
- Runtime(s): Both 2.5.0
- Plugin(s): ^1.5.1

### Please tell us how to recreate the issue in as much detail as possible.
Error Just appears  after run "tns livesync ios --watch"

**Comment by NickIliev** [comment]
Hey @MalinGunasekara 

As of today NativeScript-CLI has new release 2.5.0. Please update your NativeScript and rebuild your application with reset modules and platforms.
TO do this tfollow these steps:

```
npm uninstall -g nativescript
npm cache clean
npm install -g nativescript

tns platform remove ios
rm -rf platforms
rm -rf node_modules

tns platform add ios
tns build ios
tns run ios 

```
Note that from nativeScript 2.5.0  `tns run ios` will work as livesync and livesync is now depreceated. So you can simply run your app and by default it wll watch and deploy uyour changes (even those in **node_modules** folder)

**Comment by MalinGunasekara** [comment]
hey @NickIliev  

It worked... \m/  
Thank You......
