### ISSUE TITLE
Cant resize TabView Icon Size

### ISSUE THREAD

**Issue by ezequielzacca** [telerik/nativescript-ui-samples#170]
### Tell us about the problem
I cant set the TabViewItem icon size

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.0
- Cross-platform modules: 2.5.0
- Runtime(s): 2.5.0

Ive tried to change the image size, but it doenst seems to change the size when the image is rendered inside the tabview, no matter what the size of the image is, it always shows the exactly same size on my phone (Android)

```
<ActionBar title="test">
    <StackLayout orientation="horizontal"
                 ios:horizontalAlignment="center"
                 android:horizontalAlignment="center">
        <Image src="res://nativescript_logo" class="action-image"></Image>
        <Label text="ativeScript" class="action-label"></Label>
    </StackLayout>
</ActionBar>
<TabView tabsBackgroundColor="#e53e00" selectedColor="white" tabTextColor="white" selectedTabTextColor="white" >
    <template tabItem title="Listings" iconSource="~/images/map.png">
        <StackLayout>
            <Label text="First tab item"></Label>
        </StackLayout>
    </template>    
    <template tabItem title="Listings3" iconSource="~/images/map.png">
        <StackLayout>
            <Label class="mdi" [text]="'mdi-favorite' | fonticon"></Label>
        </StackLayout>
    </template>
</TabView>
```

![screenshot_20170216-083419 1](https://cloud.githubusercontent.com/assets/1986425/23030660/2681cac2-f44d-11e6-8702-cd7ad6e975e2.png)

**Comment by ginev** [comment]
@ezequielzacca this seems to not be the right place to post this issue. This repository holds the Telerik UI for NativeScript SDK examples. If you have feedback regarding Telerik UI for NativeScript, please use the https://github.com/telerik/nativescript-ui-feedback repository for issues. For NativeScript related issues, take a look at www.nativescript.org and the support channels provided there.
