### ISSUE TITLE
Feature Request: Calendar highlight special days

### ISSUE THREAD

**Issue by deneshr** [telerik/nativescript-ui-samples#172]
Currently we are unable to highlight special days in the calendar such as public holidays.
Is there any way we could style specific days with a different color perhaps?

**Comment by ginev** [comment]
Hello @deneshr,

we have logged this in our TODO list. I will move this issue to the dedicated GitHub repository for NativeScript UI issues (as this one contains examples only): https://github.com/telerik/nativescript-ui-feedback.
