### ISSUE TITLE
CSS is not applied to elements loaded through ui/builder and added to RadSideDrawer

### ISSUE THREAD

**Issue by alixandru** [telerik/nativescript-ui-samples#177]
### Tell us about the problem
The styles from CSS file are not applied to elements which are loaded programmatically (from javascript).

I have a page in which the content of the RadSideDrawer is build dynamically on page load. Some of the elements are custom components which are loaded through `ui/builder` and other are standard elements (like StackLayout, Label, etc). None of them have the CSS style applied, although the CSS class names are correctly set at creation.

I need to manually call `setInlineStyle` to work around this issue.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.2
- Cross-platform modules: 2.5.1
- Runtime(s): 2.5.0
- Plugin(s): nativescript-telerik-ui 1.6.1

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

    public constructor() {
	// note: the elements defined in menu.xml are correctly styled from CSS
	let menu = builder.load({
	  path: "~/utils/page/menu",
	  name: "menu",
	  page: this
	});

	this.sideDrawer = new drawerModule.RadSideDrawer();
	this.sideDrawer.drawerContent = menu;
    }

    public onLoaded() {
        /* add some more elements to drawerContent (custom and standard components) */
        /* these elements are not styled at all */
    }

**Comment by VladimirAmiorkov** [comment]
Hi @alixandru ,

I tried to reproduce the described issue but to no avail. When using the ui/builder for creating the mainContent and drawerContent of the RadSideDrawer all cssClass that are loaded from the app.css file are applied to correctly.

I attached a sample project which shows the above scenario, can you test it on your side and try to reproduce the issue in it. Let me know if I have missed something.

[sd-css-test.zip](https://github.com/telerik/nativescript-ui-samples/files/821234/sd-css-test.zip)

**Comment by ginev** [comment]
This issue was moved to telerik/nativescript-ui-feedback#112
