### ISSUE TITLE
Multiple Axis on iOS is not displaying the left axis

### ISSUE THREAD

**Issue by nguyenbn** [telerik/nativescript-ui-samples#19]
I downloaded and ran the Native Script UI Samples app at https://github.com/telerik/nativescript-ui-samples. When I ran the Multiple Axis example, I don't get a vertical axis on the left. See screenshot. It does work on Android though.
<img width="487" alt="screen shot 2015-09-16 at 3 07 02 pm" src="https://cloud.githubusercontent.com/assets/1062406/9915497/68cb02b0-5c85-11e5-8137-afba87c880f1.png">
![screen shot 2015-09-16 at 3 09 49 pm](https://cloud.githubusercontent.com/assets/1062406/9915501/6a9d72ee-5c85-11e5-9734-2ad10d06b48b.png)

**Comment by karaahmed** [comment]
Hi nguyenbn,
I've checked the multiple axes example and cannot reproduce the problem with missing axes on the left site. Could you please check and give me the version of TelerikUI.framework, nativescript-ui plugin and NativeScript runtime you use. 
Bulent

**Comment by nguyenbn** [comment]
Here's my package.json file.  I'm also on NativeScript 1.3 runtime.  Is that enough information?
```
{
	"nativescript": {
		"id": "org.nativescript.TelerikUI",
		"tns-android": {
			"version": "1.3.0"
		},
		"tns-ios": {
			"version": "1.3.0"
		}
	},
	"dependencies": {
		"nativescript-telerik-ui": "0.0.10",
		"tns-core-modules": "1.3.0"
	}
}
```

**Comment by karaahmed** [comment]
Hi nguyenbn,
I've tested the sdk example with {N} 1.3 and reproduced the problem. The missing axes should be a recently introduced bug in native chart for iOS control. We will update the npm package with fixed framework asap. Please, stay tuned.
- Bulent

**Comment by nguyenbn** [comment]
Awesome!  Thanks for looking into it.  I look forward to the release.
