### ISSUE TITLE
An example of how to use DateTimeContinuousAxis?

### ISSUE THREAD

**Issue by maury91** [telerik/nativescript-ui-samples#20]
Hi, i'm trying to use DateTimeContinuousAxis but the result is always an empty graph (except for the verticalAxis that is correct)

For the values of DateTimeContinuousAxis  i'm using the javascript Date object, i've tried with the java Calendar but the app crashes

**Comment by ginev** [comment]
Hi @maury91,

Can you share with us some more details:
- NS version
- OS you are running your NS app on: Android or iOS?

Thanks!

**Comment by maury91** [comment]
Last NS Version (1.3),
Android

**Comment by ginev** [comment]
@maury91 Can you please paste the code you are using? We've identified some potential issues that might prevent you from seeing the chart but will need to verify with what you're using in your app.

Thanks!

**Comment by lhitc** [comment]
I'm having the same issue with NativeScript 1.5.1 and nativescript-telerik-ui 0.2.3, testing on Android.

diagram-data-model.js:
```javascript
var DiagramDataModel = (function () {
    function DiagramDataModel() {
    }
    Object.defineProperty(DiagramDataModel.prototype, "timedDataSource", {
        get: function () {
            return [
				{
					timeStamp: new Date(2015, 10, 1),
					Amount: 40
				},
				{
					timeStamp: new Date(2015, 10, 3),
					Amount: 50
				},
				{
					timeStamp: new Date(2015, 10, 11),
					Amount: 30
				}
            ];
        },
        enumerable: true,
        configurable: true
    });
    return DiagramDataModel;
})();
exports.DiagramDataModel = DiagramDataModel;
```

including it in main-view-model.js (which works fine for other diagram/axis types):
```javascript
var diagramDataModule = require("./diagram-data-model");

...
this.diagram = new diagramDataModule.DiagramDataModel();
```

displaying it in main-page.xml:
```xml
...

					<chart:RadCartesianChart id="cartesianChart">
						<chart:RadCartesianChart.series>
							<chart:LineSeries items="{{ diagram.timedDataSource }}" categoryProperty="timeStamp" valueProperty="Amount">
								<chart:LineSeries.horizontalAxis>
									<chart:DateTimeContinuousAxis />
								</chart:LineSeries.horizontalAxis>
								<chart:LineSeries.verticalAxis>
									<chart:LinearAxis/>
								</chart:LineSeries.verticalAxis>
							</chart:LineSeries>
						</chart:RadCartesianChart.series>
					</chart:RadCartesianChart>

...
```

With these example data, y-Axis correctly shows a range of 0...60, but x-Axis shows nothing an nothing is plotted.
Any solution? Or maybe provide a working example in the demo app?

**Comment by karaahmed** [comment]
@lhitc
I can confirm that there is a problem with **DateTimeContinuousAxis** and we will try to fix it for next release. 
Until then you can use **DateTimeCategoricalAxis** . I tested your example with it and it works fine for iOS & Android.
There is one thing you should consider with  Date objects and it is the long format of values that you will see in your chart. Currently, if you provide date as "day/month/year" string you will see the axis labels with this format. In fact, this is the only date format that we support for now. It is ongoing task to support different date/time formats for axis & calendar control.

**Comment by lhitc** [comment]
Thanks, waiting for the next release.
DateTimeCategoricalAxis is not applicable for the use case, since the intervals between single data items vary and would give the user an incorrect visual information (which is probably why DateTimeContinuousAxis exists ;-).

Concerning axis labels: formatting surely is an essential feature. Also it should be possible to set intervals for labeling. For example when displaying a full month in a DateTime based diagram you wouldn't want every single date as a label on the X-axis but rather every 7th day.
