### ISSUE TITLE
Linear axis is not showing min to max range

### ISSUE THREAD

**Issue by nguyenbn** [telerik/nativescript-ui-samples#21]
I am trying to get a chart to display from 0-100 in iOS.  I'm not able to get the chart to display that full range.  Here is my code:
```
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded"  xmlns:chart="nativescript-telerik-ui/chart">
    <chart:CartesianChart>
      <chart:CartesianChart.series>
        <chart:BarSeries items="{{ CPUStatsSource }}" categoryProperty="time" valueProperty="value">
            <chart:BarSeries.horizontalAxis>
                <chart:DateTimeCategoricalAxis plotMode="BetweenTicks" majorTickInterval="5" />
            </chart:BarSeries.horizontalAxis>
            <chart:BarSeries.verticalAxis>
                <chart:LinearAxis horizontalLocation="Left" minimum="0" maximum="100" />
            </chart:BarSeries.verticalAxis>
        </chart:BarSeries>
      </chart:CartesianChart.series>
    </chart:CartesianChart>
</Page>
```

Here is what I'm seeing:

<img width="487" alt="screen shot 2015-09-22 at 2 57 25 pm" src="https://cloud.githubusercontent.com/assets/1062406/10028409/5042c61a-613a-11e5-92fe-85653cd02b07.png">

I'm using the following:
- "nativescript-telerik-ui": "0.0.10",
- "tns-core-modules": "1.3.0"

**Comment by karaahmed** [comment]
Hi nguyenbn,

You can set the step of ticks with "majorStep" property of linear axis as it follows:

	<chart:LinearAxis horizontalLocation="Left" minimum="0" maximum="100" majorStep="1" />

However, I found a bug in linear axis implementation that leads to wrong range if 0 is used as minimum value. It will be fixed for next release, but if it is critical for your application you can fix it locally in 

	<app_folder>/node_modules/nativescript-telerik-ui/chart/chart.ios.js 
file.
Just update the condition check of onMinimumChanged function of LinearAxis object at line:331 from

	if (data.newValue) 
to 
	
	if (data.newValue !== '')

Please, let me know if this helps.

Bulent

**Comment by karaahmed** [comment]
Bug is fixed in ver. 0.0.11
