### ISSUE TITLE
Put hamburger icon in place of navigationButton when SideDrawer is present

### ISSUE THREAD

**Issue by lscown** [telerik/nativescript-ui-samples#22]
Hey guys,

It would be great to see (for android especially) the hamburger menu icon appear in the navigation bar on pages with the SideDrawer, or when triggered to.

I realise you can do this right now by using a button in the action bar, however, you can't currently left align buttons on {N} with Android.

Is there any plan for this?

**Comment by ginev** [comment]
Hi @lscown,

This is a known limitation and it is something on our TODO list so stay tuned.

Thanks!

**Comment by lscown** [comment]
Something I'd like to mention as well - not sure about how you're going to do it anyway. There's some cases where we'd want the Navigate Back button to override the hamburger menu, but still have the SideDrawer present (can be seen on certain Android apps when adding to the back stack). However the navigate back button and hamburger button should never coexist.  :-)

**Comment by alexrainman** [comment]
There's a way to this guys:

<Page.actionBar>
    <ActionBar title="Title">
      <android:NavigationButton icon="res://ic_menu_black" tap="toggleSideDrawer" />
      <ActionBar.actionItems>
        <iOS>
          <ActionItem icon="res://ic_menu_black" ios.position="left" tap="toggleSideDrawer" />
        </iOS>
      </ActionBar.actionItems>
    </ActionBar>
  </Page.actionBar>

**Comment by RichardSilveira** [comment]
It does not work for me...
Are you emulating for Android @alexrainman ?

**Comment by NathanWalker** [comment]
Just for reference, an example of how to do this (using hamburger menu with icon fonts) and Angular2 + {N} w/ `RadSideDrawer`:
https://gist.github.com/NathanWalker/e8f4f7c42af04fc725764a9867936e3d

**Comment by codeback** [comment]
@NathanWalker, in your example, the menu button is shown on the right side in Android. 

Following this article http://docs.nativescript.org/angular/ui/action-bar#creating-slidedrawer-button, we should do it with NavigationButton on Android and with ActionItem in ios.

But with NavigationButton, I don't know how to use icon fonts.

Any ideas?

**Comment by Gerralt** [comment]
@NathanWalker I'm wondering the same thing as @codeback 
I'd love to have my ng2-fonticon powered actionitem on the left side of the navbar...
