### ISSUE TITLE
Xcode 7 fails to submit builds to iTunes because of simulator in Info.plist

### ISSUE THREAD

**Issue by maknz** [telerik/nativescript-ui-samples#23]
As discussed with some of the iOS team from Telerik already, the TelerikUI.framework that ships in the nativescript-telerik-ui npm package (as of 0.0.10) has an invalid value in the Info.plist.

> Invalid Bundle - Info.plist of “mobile.app/Frameworks/TelerikUI.framework” specifies a simulator platform for the CFBundleSupportedPlatforms key...

This is the same issue that cropped up recently in the Google Maps SDK: https://code.google.com/p/gmaps-api-issues/issues/detail?id=8568

Our solution was to remove the whole CFBundleSupportedPlatforms key from the plist file. This makes the sidedrawer work seemingly fine in the simulator, on the device, and for iTunes submission. The TelerikUI.framework Info.plist has always specified the simulator for that value, it just seems that since Xcode 7 / iOS 9 that Apple is validating that harder.

For now, as above, we just removed that entry in the plist file and committed node_modules so we can keep the change around. A more permanent solution would be good though.

Thanks!

**Comment by ginev** [comment]
Hi @maknz,

Thanks for the feedback. This is on the TODO list.

**Comment by sowrabhbs** [comment]
I am facing same issue,after I upload build to itunes connect,it says build is invalid and got a mail which says
Invalid Bundle - A nested bundle contains simulator platform listed in CFBundleSupportedPlatforms Info.plist key.
Xcode 7
