### ISSUE TITLE
Feature request: SideDrawer toggle method

### ISSUE THREAD

**Issue by alexrainman** [telerik/nativescript-ui-samples#25]
Very useful to be called from ActionBar android:NavigationButton and iOS ActionItem left positioned.

**Comment by NikolayVasilev** [comment]
Such method already exists in our latest plugin version. calling toggleDrawerState() will open the drawer if closed and close it if open.

**Comment by alexrainman** [comment]
Awesome. Please document it so the rest of the world know it. I have couple suggestion. May i use a new thread?

**Comment by NikolayVasilev** [comment]
The update will be included in our next documentation upload. 

As for new suggestions, you can use a new thread or post it in this one.

**Comment by alexrainman** [comment]
I see you are planning to make SideDrawer able to go on top of ActionBar, that's awesome. I think you need to make it able to go behind the screen too, like LinkedIn app for example. In my opinion, navigation drawer android style in iOS looks ugly ;-)
