### ISSUE TITLE
RadSideDrawer/RadListView issue

### ISSUE THREAD

**Issue by alexrainman** [telerik/nativescript-ui-samples#26]
Anytime i try to use RadListView or anything else inside SideDrawer.mainContent i get this error:

```
2015-10-18 12:25:35.681 node[8678:414270] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-8208/DVTFoundation/PlugInArchitecture/PlugInManager/DVTPlugInManager.m:257
Details:  Requested but did not find extension point with identifier Xcode.DVTFoundation.DevicePlatformMapping
Object:   <DVTPlugInManager: 0x100b11060>
Method:   -extensionPointWithIdentifier:
Thread:   <NSThread: 0x10220a990>{number = 1, name = main}
```

For example, this works:

```
<drawer:RadSideDrawer.mainContent>
      <lv:RadListView items="{{ colors }}">
          <lv:RadListView.itemTemplate>
          </lv:RadListView.itemTemplate>
      </lv:RadListView>
</drawer:RadSideDrawer.mainContent>
```

But once i try to add any content inside itemTemplate i get the issue.

Same thing happens if i try to add a TabView inside RadSideDrawer mainContent:

```
<drawer:RadSideDrawer.mainContent>
      <TabView>
        <TabView.items>
          <TabViewItem title="Tab 1">
            <TabViewItem.view>
              <Label text="Label in Tab1" />
            </TabViewItem.view>
          </TabViewItem>
          <TabViewItem title="Tab 2">
            <TabViewItem.view>
              <Label text="Label in Tab2" />
            </TabViewItem.view>
          </TabViewItem>
        </TabView.items>
      </TabView>
</drawer:RadSideDrawer.mainContent>
````

I get the error:

```
2015-10-18 12:32:38.022 node[8979:424675] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-8208/DVTFoundation/PlugInArchitecture/PlugInManager/DVTPlugInManager.m:257
Details:  Requested but did not find extension point with identifier Xcode.DVTFoundation.DevicePlatformMapping
Object:   <DVTPlugInManager: 0x100c78d80>
Method:   -extensionPointWithIdentifier:
Thread:   <NSThread: 0x102a0cde0>{number = 1, name = main}
```

Help please!

**Comment by alexrainman** [comment]
Same thing if i want to use observableArray:

```
this._items = new observableArray.ObservableArray();
for (var i = 0; i < 10; i++) {
    this.items.push(new DataItem(i, "Item " + i, "This is item description."));
}
```
:(

**Comment by alexrainman** [comment]
Conclusion: you can not use TabView inside RadSideDrawer mainContent in iOS.

```
2015-10-20 08:40:13.616 node[21873:1045598] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-8208/DVTFoundation/PlugInArchitecture/PlugInManager/DVTPlugInManager.m:257
Details:  Requested but did not find extension point with identifier Xcode.DVTFoundation.DevicePlatformMapping
Object:   <DVTPlugInManager: 0x102162b60>
Method:   -extensionPointWithIdentifier:
Thread:   <NSThread: 0x100b03e50>{number = 1, name = main}
```

**Comment by ginev** [comment]
Hi @alexrainman ,

Sorry for the late reply.

Can you please zip your NS app and send it to us for further investigation?

Also, can you please share some further details about the issues you are experiencing when using the code snippet below:

```
for (var i = 0; i < 10; i++) {
    this.items.push(new DataItem(i, "Item " + i, "This is item description."));
}
```

This will help us better understand the cases and see how we can help.

**Comment by alexrainman** [comment]
@ginev i don't have problems with that piece of code. I had issues with array.splice() so i ended up using this:

```
for (var i = 0; i < that.get()._items.length; i++) {
    that.get()._items.pop();
}
```

I know that array.splice() is now fixed, don't?

The issue i have is TabView inside SideDrawer.mainContent in iOS throws this issue:

```
2015-10-20 08:40:13.616 node[21873:1045598] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-8208/DVTFoundation/PlugInArchitecture/PlugInManager/DVTPlugInManager.m:257
Details:  Requested but did not find extension point with identifier Xcode.DVTFoundation.DevicePlatformMapping
Object:   <DVTPlugInManager: 0x102162b60>
Method:   -extensionPointWithIdentifier:
Thread:   <NSThread: 0x100b03e50>{number = 1, name = main}
```

You can download my testing project from this link: https://drive.google.com/file/d/0B6hZDQudMRBUX0lUTGc1ZmlhZVE/view?usp=sharing

My testing allowed me to detect another issues and make some suggestions to {N} team:

- Swipe actions are not visible in Android even running your sdk example (i guess because this is a preview product)
- TabView needs to be flexible enough to make it based on simple fragments and not ViewPager when swiping tabs is not needed/wanted by the developer.

**Comment by alexrainman** [comment]
Let's merge my issues related to RadListView in one place :) The issue i am facing now is after updating {N} CLI, recyclerview cannot be found even changing gradle.build :(

**Comment by ginev** [comment]
Hi @alexrainman ,

I have managed to run your application.

1. The reason for not correctly seeing the Swipe views is simple: you have put the RadListView control in a Tab control. The Tab control processes the same gestures that are needed to reveal the swipe views. So you have two options here:
 a. Either disable the Swipe functionality if you want to use a Tab control
 b. Remove the Tab control and use a strip of Tab-styled buttons to switch between tab views without relying on a swipe gesture to swipe between views. This will allow you to use Swipe-to-Execute in your LIstView.

A recommended practice is to avoid nesting controls that use the same gestures to perform an action.

2. I am still not able to determine the situation with the RecyclerView. On my side, I had problems with having the dependency defined with an explicit version - as you have done to resolve it. I think you just need to make sure you have API level 23 from the Android SDK manager installed, as well as the latest version of the support repository.

**Comment by alexrainman** [comment]
@ginev Swipe views are not visible on Android even doing this:

```
<drawer:RadSideDrawer.mainContent>
        <lv:RadListView items="{{ dataItems }}" row="1"
                        pullToRefresh="true"
                        shouldRefreshOnPull="{{ onShouldRefreshOnPull }}"
                        loadOnDemandMode="Auto"
                        shouldLoadMoreData="{{ onLoadMoreItemsRequested }}"
                        selectionBehavior="None"
                        itemTap="{{ onItemClick }}"
                        swipeCells="true"
                        startSwipeCell="{{ onSwipeCellStarted }}"
                        didFinishSwipeCell="{{ onSwipeCellFinished }}">
            <lv:RadListView.listViewLayout>
                <lv:ListViewLinearLayout itemHeight="50" scrollDirection="Vertical"/>
            </lv:RadListView.listViewLayout>
            <lv:RadListView.itemTemplate>
                <StackLayout orientation="vertical">
                    <Label fontSize="20" text="{{ itemName }}" cssClass="cellTitle" />
                    <Label fontSize="14" text="{{ itemDescription }}" cssClass="cellDetail" />
                </StackLayout>
            </lv:RadListView.itemTemplate>
            <lv:RadListView.itemSwipeTemplate>
                <GridLayout columns="auto, *, auto">
                    <Button col="0" cssClass="cellLeftBtn" text="Fold"/>
                    <Button col="2" cssClass="cellRightBtn" text="Delete"/>
                </GridLayout>
            </lv:RadListView.itemSwipeTemplate>
        </lv:RadListView>
    </drawer:RadSideDrawer.mainContent>
```

They are not visible even removing SideDrawer and using RadListView directly in the page.

I am just trying to build a complex UI and find out how this thing respond to it.

Question: why i have to wrap RadListView in StackLayout to make it visible in Android when used inside RadSideDrawer.mainContent/TabView?

Question: is it possible to disable swipe in a TabView or build it based on simple fragments and not ViewPager?

Question: are you planning to provide a carousel view based on ViewPager and UIPageViewController?
If not i will go ahead and try to do it myself and give it back to the community :)

**Comment by ginev** [comment]
Hi @alexrainman ,

We do plan to expose carousel functionality in RadListView so stay tuned.

BTW, are there any further issues related to Swipe templates on your side?

Greets!
