### ISSUE TITLE
RadListView: swipe to edit buttons not visible in Android

### ISSUE THREAD

**Issue by alexrainman** [telerik/nativescript-ui-samples#28]
I am testing swipe to execute functionality with tow buttons left/right. They are visible on iOS but in Android only white space when you swipe. Any help?

**Comment by alexrainman** [comment]
Cells separator line is not visible on Android neither. I guess this is a work in progress. Thanks.

**Comment by ginev** [comment]
Hello @alexrainman ,

1. Can you paste the XML you are using to define your Swipe UI here for further investigation?

2. Separators are not supported on Android as of now. My suggestion would be to define a separator as a part of the `itemTemplate`. What I am thinking right now is that we need to basically disable them in iOS by default and publish a help article that describes how this is done using an `itemTemplate`.

**Comment by alexrainman** [comment]
I already provided you with the sample code link in another thread. Please, provide me example on how to achieve separators with itemTemplate.
Why to disable separators in iOS and not to enable them in Android instead?
I guess it will be easier to declare them as a property of itemTemplate with the ability to configure color, height and visibility.

**Comment by ginev** [comment]
Hi @alexrainman,

since we have discussed this topic in issue #26 I am going to close this one for better visibility.
