### ISSUE TITLE
Side drawer crash

### ISSUE THREAD

**Issue by thstarshine** [telerik/nativescript-ui-samples#3]
Frequently sliding the side drawer in and out makes it crash sometimes.

Reproduce:
1. slide the side drawer out
2. swipe it back
3. before 2. is finished, try to slide the drawer out again
4. it should just flash for a second and disappear

**Comment by ginev** [comment]
Hi @thstarshine and thanks for reporting this issue.
Can you please clarify which platform does the SD crash on? Is it Android or iOS, or both?

**Comment by thstarshine** [comment]
Hi @ginev  Sorry I should be more specific.
It happened on Android however I've got no Apple device to test if it would happen on iOS as well.
Thank you very much.

**Comment by manijak** [comment]
I've managed to reproduce this on iOS as well.

**Comment by ginev** [comment]
Thanks @manijak and @thstarshine. We are going to look into this.
