### ISSUE TITLE
Crash on partial back navigate swipe on iOS on 0.1.0

### ISSUE THREAD

**Issue by maknz** [telerik/nativescript-ui-samples#30]
If you have a sidedrawer on a page which has a page to navigate back to, and you start doing the swipe-to-go-back gesture, but let go in the middle of it, the app will crash with

```
the queue, or the queue is temporarily busy or suspended
file:///app/tns_modules/ui/core/view-common.js:841:101: JS ERROR Error: View already has a parent. View: ContentView Parent: RadSideDrawer
1   0x10fb601de NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x1101203c9 ffi_closure_unix64_inner
3   0x1101231be ffi_closure_unix64
4   0x111202940 -[UIViewController __viewWillAppear:]
5   0x11122244e -[UIViewController(UIContainerViewControllerProtectedMethods) cancelBeginAppearanceTransition]
6   0x11123d0cd -[UINavigationController _navigationTransitionView:didCancelTransition:fromViewController:toViewController:wrapperView:]
7   0x1112330d7 __49-[UINavigationController _startCustomTransition:]_block_invoke
8   0x111a211e9 -[_UIViewControllerTransitionContext completeTransition:]
9   0x11105a63a __53-[_UINavigationParallaxTransition animateTransition:]_block_invoke93
10  0x111117daa -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:]
11  0x1110f63a7 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:]
12  0x1110f6756 -[UIViewAnimationState animationDidStop:finished:]
13  0x1250b91ea -[UIViewAnimationStateAccessibility animationDidStop:finished:]
14  0x116011d70 CA::Layer::run_animation_callbacks(void*)
15  0x113d0449b _dispatch_client_callout
16  0x113cec34b _dispatch_main_queue_callback_4CF
17  0x112f713e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
18  0x112f32939 __CFRunLoopRun
19  0x112f31e98 CFRunLoopRunSpecific
20  0x115acbad2 GSEventRunModal
21  0x111071676 UIApplicationMain
22  0x11012303c ffi_call_unix64
23  0x11f3dd600
```

This was supposedly fixed in 0.1.0 but we can still reproduce it consistently. I removed lib/ and ensured that the prepare got run for it, by doing an `npm i` followed by a `tns prepare ios`:

```
The iOS Deployment Target is now 8.0 in order to support Cocoa Touch Frameworks.
Successfully prepared plugin nativescript-telerik-ui for ios.
```

**Comment by NikolayVasilev** [comment]
Hello Regan,

Thank you for reporting this. Would it be possible to specify the exact
NativeScript version you are using as well as the plugin version for UI for
NativeScript? If it is not the latest on, can you try upgrading and see if
you still get the same behavior?
It would also be really helpful if you can provide the exact steps to
reproducing it, since this issue should be fixed, and we are unable to
reproduce it on our side.

Thank you in advance.
Regards,
NIkolay Vasilev

**Comment by maknz** [comment]
1.4.1 CLI, 1.4.0 Android and iOS runtimes. 0.1.0 nativescript-telerik-ui. I'm sure that the new TelerikUI.framework is being used as our code is using RadSideDrawer, which wouldn't work if 0.1.0 wasn't being used. Hope that helps.

I see there's a new CLI out (1.4.2), I will upgrade to this tomorrow and try.

**Comment by NikolayVasilev** [comment]
Hi, 

Have you had the chance to try this out with the latest CLI?

**Comment by maknz** [comment]
Indeed, I can't seem to replicate this on the latest CLI. I will re-open if I see it appear. Thanks.
