### ISSUE TITLE
RadListView not rendering Images

### ISSUE THREAD

**Issue by bradmartin** [telerik/nativescript-ui-samples#32]
First the standard ListView which works correctly

              <ListView id="userList" items="{{ users }}" row="1" loadMoreItems="loadMoreUsers">
                    <ListView.itemTemplate>
                      <GridLayout columns="auto, *" rows="auto, auto, *" cssClass="margin-10">
                        <StackLayout row="0" colSpan="2">
                          <Image src="{{ Image }}" stretch="aspectFit" horizontalAlignment="center" style="height:250"/>
                        </StackLayout>
                        <Label text="{{ Name }}" cssClass="roboto font-20 primary-500 margin-left-10" row="1" colSpan="2" />
                        <GridLayout row="2" rows="auto" columns="auto, auto, auto" cssClass="margin-left-10">
                          <Button text="PROFILE" row="0" col="0" tap="forgotPassword" cssClass="link" />
                          <Button text="MESSAGE" row="0" col="1" tap="showMsgFooter" cssClass="link accent-500" />
                        </GridLayout>
                      </GridLayout>
                    </ListView.itemTemplate>
                  </ListView>

The RadListView using the similar layout but only the text appears, the Images never render.

       

The bindings are working correctly as the standard ListView widget works correctly. So I'm trying to achieve a more simplified layout per 'Material Design' to render images in a GridList so using the RadListView the following is needed to work

        <lv:RadListView items="{{ users }}" >
                    <lv:RadListView.listViewLayout>
                      <lv:ListViewGridLayout spanCount="3" itemHeight="60" scrollDirection="Vertical" />
                    </lv:RadListView.listViewLayout>
                    <lv:RadListView.itemTemplate>
                      <Image src="{{ Image }}" stretch="aspectFit" horizontalAlignment="center" />
                    </lv:RadListView.itemTemplate>
                  </lv:RadListView>

**Comment by ginev** [comment]
Hi @bradmartin ,
The last paragraph of your post suggests that you've managed to resolve your issue. Anyway, could it be possible that you attach a ZIP archive which I can use to reproduce the first scenario so that I can make sure it's not related to any major problems to RadListView?

You can upload on DropBox or simply let me know how to reproduce it via a step-by-step guide.

Thanks!

**Comment by upender-devulapally** [comment]
Hi URL based Images are not rendering in RadListView but working fine when we use ListView, images are rendering only when we do some action on RadListView(i.e scrolling the list) then images are rendering.Can any one help me here ?

**Comment by upender-devulapally** [comment]
Working fine when used ObservableArray on list
