### ISSUE TITLE
Observable elements are not refreshed on the screen when they change

### ISSUE THREAD

**Issue by stonecourier** [telerik/nativescript-ui-samples#34]
Tried getting this to work in my project and it does not. So amended the sdk example to show.

This is from swipe_execute_model.ts.

Modified DataItem so it is observable, changed itemDescription. 

If you swipe it raises an alert.

Change is reflected on get, but the UI does not change.

<pre>
import observableArray = require("data/observable-array");
import observable = require("data/observable");

export class ViewModel {

     _items: observableArray.ObservableArray&lt;DataItem&gt;;

    constructor() {
        this.initDataItems();
    }

    get dataItems() {
        return this._items;
    }

    public onCellSwiping(args: any) {
        var swipeLimits = args.data.swipeLimits;

        if (args.data.x &gt; 100){
            console.log("Threshold achieved: " + args.data.x);
        }else if(args.data.x &lt; -100){
            console.log("Threshold achieved: " + args.data.x );
        }
    }

    public onSwipeCellStarted(args: any) {
        var swipeLimits = args.data.swipeLimits;
        console.log("Started swipe cell: " + args.object);
        swipeLimits.threshold = 100;

    }

    public onItemClick(args: any){
        console.log("Item click: " + args.itemIndex);
    }

    public onSwipeCellFinished(args: any) {
        var swipeLimits = args.data.swipeLimits;
        console.log("Started swipe cell: " + args.object);
        swipeLimits.threshold = 100;
        swipeLimits.left = 150;
        swipeLimits.right = 150;

    // Raise alert, just to check that it is being triggered
        this._items.getItem(args.itemIndex).set("itemDescription", "Swiped");
        alert("index : " + args.itemIndex.toString() + ", itemDescription :" + this._items.getItem(args.itemIndex).get("itemDescription"));
    }

    private initDataItems() {
        this._items = new observableArray.ObservableArray&lt;DataItem&gt;();

        for (var i = 0; i &lt; 50; i++) {
            this._items.push(new DataItem(i, "Item " + i, "This is item description."));
        }
    }
}

export class DataItem extends observable.Observable {
    public id: number;
    public itemName;
    public itemDescription;

    constructor(id: number, name: string, description: string) {
        super();
        this.id = id;
        this.itemName = name;
        this.set("itemDescription",description);
    }
}
</pre>

**Comment by ginev** [comment]
@stonecourier,

The issue has been reproduce and is being investigated.

Thanks for your feedback!

**Comment by ginev** [comment]
Hello @stonecourier : I would like to inform you that we're now aware of what causes this problem and will work on fixing it. We will publish an update of Telerik UI for NS as soon as it's done.
