### ISSUE TITLE
itemTap always triggers twice

### ISSUE THREAD

**Issue by stonecourier** [telerik/nativescript-ui-samples#36]
At least it does on Android. Amended sdk example item-layouts-linear.

Displays alert twice.

Javascript

<pre>

var viewModel = require("./item-layouts-model");
function onPageLoaded(args) {
    var page = args.object;
    page.bindingContext = new viewModel.ViewModel();
}
exports.onPageLoaded = onPageLoaded;

var counter = 1;
function itemTap(args) {
    alert("tapped" + counter);
	counter++;
}
exports.itemTap = itemTap;

</pre>
Xml

<pre>
&lt;Page loaded="onPageLoaded" xmlns:lv="nativescript-telerik-ui/listview" xmlns="http://www.nativescript.org/tns.xsd"&gt;
    &lt;lv:RadListView items="{{ dataItems }}" itemTap="itemTap"&gt;
        &lt;lv:RadListView.listViewLayout&gt;
            &lt;lv:ListViewLinearLayout itemHeight="50" scrollDirection="Vertical"/&gt;
        &lt;/lv:RadListView.listViewLayout&gt;
        &lt;lv:RadListView.itemTemplate&gt;
            &lt;StackLayout orientation="vertical"&gt;
                &lt;Label fontSize="20" text="{{ itemName }}"/&gt;
                &lt;Label fontSize="14" text="{{ itemDescription }}"/&gt;
            &lt;/StackLayout&gt;
        &lt;/lv:RadListView.itemTemplate&gt;
    &lt;/lv:RadListView&gt;
&lt;/Page&gt;

</pre>

**Comment by ginev** [comment]
Hi @stonecourier, this is a known issue and it's already fixed in our internal codebase. It will be published in our next update.

Let us know in case of further questions.
