### ISSUE TITLE
ListView ItemLayouts do not seem to be able to be set via code.

### ISSUE THREAD

**Issue by stonecourier** [telerik/nativescript-ui-samples#38]
From the release notes, it certainly implies that we can set layouts via code.

http://docs.telerik.com/devtools/nativescript-ui/Controls/ListView/listview-features-item-layouts

But I cannot seem to get it to work, for the grid view example taken from the samples.

<pre>
var viewModel = require("./item-layouts-model");
var listViewModule = require("nativescript-telerik-ui/listview");

function onPageLoaded(args) {
    var page = args.object;
    page.bindingContext = new viewModel.ViewModel();

	var listView = page.getViewById("listView");
var layout = new listViewModule.ListViewGridLayout();
layout.spanCount = 3;
layout.scrollDirection = "horizontal";
listView.listViewLayout = layout;

}
exports.onPageLoaded = onPageLoaded;

</pre>

This just comes up as the standard listview.

**Comment by karaahmed** [comment]
We are in the middle of refactoring of ListView and will handle this issue too. 
We are going to publish an updated release soon.

**Comment by stonecourier** [comment]
Ideally if we could make the grid view so we can define a set width and it figures out how many columns it can fit, it would be good. Want to use this for an image gallery.

**Comment by ginev** [comment]
Hi @stonecourier 
currently the Grid layout works by requiring you to explicitly say how many columns/rows would you like to have. What you are talking about sounds more like a Wrap layout which is on our TODO list.
