### ISSUE TITLE
Setting color for palette entry to "orange" crashes app in android.

### ISSUE THREAD

**Issue by stonecourier** [telerik/nativescript-ui-samples#39]
Occurs for pie charts. In the previous release, I raised a bug that palette entry colors were ignored.

From looking at the error message "orange" isn't a known color in android. Other colors are also a problem.

Setting the colors via hex, seems to work fine (just to be clear, this isn't a Upper/:Lower case issue).

<pre>
&lt;chart:RadCartesianChart.palettes&gt;
            &lt;chart:Palette seriesName="pie"&gt;
              &lt;chart:Palette.entries&gt;
                &lt;chart:PaletteEntry fillColor="Red" strokeColor="Black" strokeWidth="0"/&gt;
                &lt;chart:PaletteEntry fillColor="Green" strokeColor="Black" strokeWidth="0"/&gt;
                &lt;chart:PaletteEntry fillColor="Blue" strokeColor="Black" strokeWidth="0"/&gt;
                &lt;chart:PaletteEntry fillColor="#FFA500" strokeColor="Black" strokeWidth="0"/&gt;
                &lt;chart:PaletteEntry fillColor="#00FFFF" strokeColor="Black" strokeWidth="0"/&gt;
                &lt;chart:PaletteEntry fillColor="#FFC0CB" strokeColor="Black" strokeWidth="0"/&gt;
                &lt;chart:PaletteEntry fillColor="#800080" strokeColor="Black" strokeWidth="0"/&gt;
                &lt;chart:PaletteEntry fillColor="#808080" strokeColor="Black" strokeWidth="0"/&gt;
                &lt;chart:PaletteEntry fillColor="#FFFF00" strokeColor="Black" strokeWidth="0"/&gt;
                &lt;chart:PaletteEntry fillColor="#90EE90" strokeColor="Black" strokeWidth="0"/&gt;
                &lt;chart:PaletteEntry fillColor="#ADD8E6" strokeColor="Black" strokeWidth="0"/&gt;
                &lt;chart:PaletteEntry fillColor="#00FFFF" strokeColor="Black" strokeWidth="0"/&gt;
                &lt;chart:PaletteEntry fillColor="#9ACD32" strokeColor="Black" strokeWidth="0"/&gt;
              &lt;/chart:Palette.entries&gt;
            &lt;/chart:Palette&gt;
            &lt;/chart:RadCartesianChart.palettes&gt;
</pre>

**Comment by karaahmed** [comment]
We know about this issue and it is already fixed and will be included in the next build.
Instead of native android.graphics.Color.parseColor() method we use the Color module from tns_modules that support a wider range of named colors. You can check the supported list in tns-core-modules/color/known_color.js file.
