### ISSUE TITLE
Feature request: toggleDrawer() & transition xml property

### ISSUE THREAD

**Issue by manijak** [telerik/nativescript-ui-samples#4]
It would be usefull to have a toggleDrawer() method also. It would open the drawer if it is closed, and close it if it is open. 

The way it's now we have to deal with states manually in the view where sidedrawer is added, gets very repetetive in apps with over 10 views. 

Also, the option to choose transition style via xml. The reason same as above, we have to override this via code for each view. 

I tried setting  drawerTransition="PushTransition" in xml, and got the following exception:

/app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js:59:65: JS ERROR TypeError: value.getNativeContent is not a function. (In 'value.getNativeContent()', 'value.getNativeContent' is undefined)
1   0x951f0 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)

**Comment by manijak** [comment]
Update: The correct xml-attribute for transitions is, for some reason:  drawerTransitionBase="..."

**Comment by manijak** [comment]
Spoke too soon, drawerTransitionBase has no effect, seems to be the default transition I saw. 

Please fix drawerTransition attribute sidedrawer

/app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js:59:65: JS ERROR TypeError: value.getNativeContent is not a function. (In 'value.getNativeContent()', 'value.getNativeContent' is undefined)
1 0x951f0 NativeScript::FFICallbackNativeScript::ObjCMethodCallback::ffiClosureCallback(ffi_cif, void, void*, void)

**Comment by ginev** [comment]
Thanks @manijak for your feedback.
1. We will extend the API and introduce a `toggleDrawer()` method.
2. There is actually a way to set transition via XML. Transitions are objects and are set as follows:
```XML
<drawer:SideDrawer.drawerTransition>
    <tsd:ScaleUpTransition/>
</drawer:SideDrawer.drawerTransition>
```

**Comment by manijak** [comment]
Thanks ginev, that worked :+1:   Had to change the "tsd" to "drawer", needs to match the xmlns name of the sidedrawer. 

Would be great if you updated the documentation, didn't know this was possible. 
http://docs.telerik.com/devtools/nativescript-ui/Controls/SideDrawer/sidedrawer-getting-started

**Comment by ginev** [comment]
@manijak, the docs will be updated.
Thanks for the feedback.

**Comment by NikolayVasilev** [comment]
Feature will be available with the next plugin update
