### ISSUE TITLE
RadListView error at build and livesync for Android

### ISSUE THREAD

**Issue by guillaume-roy** [telerik/nativescript-ui-samples#44]
Hello,

I have an issue with RadListView when i try to livesync or run my app.

* On 'tns run android' :
<pre>
Executing before-prepare hook from C:\Users\XXX\Documents\Perso\Dev\XXX\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 1.7.3
Project successfully prepared

:config phase:  createDefaultIncludeFiles
        +found plugins: nativescript-telerik-ui

:config phase:  createPluginsConfigFile
        +creating product flavors include.gradle file in configurations folder...

:config phase:  pluginExtend
        +applying configuration from: C:\Users\XXX\Documents\Perso\Dev\XXX\platforms\android\configurations\include.gradle
        +applying configuration from: C:\Users\XXX\Documents\Perso\Dev\XXX\platforms\android\configurations\nativescript-telerik-ui\include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
        +adding dependency: C:\Users\XXX\Documents\Perso\Dev\XXX\platforms\android\libs\aar\Chart-2015.3.1209-trial-release.aar
        +adding dependency: C:\Users\XXX\Documents\Perso\Dev\XXX\platforms\android\libs\aar\Common-2015.3.1209-trial-release.aar
        +adding dependency: C:\Users\XXX\Documents\Perso\Dev\XXX\platforms\android\libs\aar\Data-2015.3.1209-trial-release.aar
        +adding dependency: C:\Users\XXX\Documents\Perso\Dev\XXX\platforms\android\libs\aar\List-2015.3.1209-trial-release.aar
        +adding dependency: C:\Users\XXX\Documents\Perso\Dev\XXX\platforms\android\libs\aar\Primitives-2015.3.1209-trial-release.aar
:preBuild UP-TO-DATE
:preNativescript-telerik-uiDebugBuild UP-TO-DATE
:checkNativescript-telerik-uiDebugManifest
:preNativescript-telerik-uiReleaseBuild UP-TO-DATE
:prepareChart201531209TrialReleaseLibrary
:prepareComAndroidSupportAppcompatV72310Library
:prepareComAndroidSupportRecyclerviewV72310Library
:prepareComAndroidSupportSupportV42310Library
:prepareCommon201531209TrialReleaseLibrary
:prepareData201531209TrialReleaseLibrary
:prepareList201531209TrialReleaseLibrary
:preparePrimitives201531209TrialReleaseLibrary
:prepareNativescript-telerik-uiDebugDependencies
:compileNativescript-telerik-uiDebugAidl
:compileNativescript-telerik-uiDebugRenderscript
:generateNativescript-telerik-uiDebugBuildConfig
:cleanLocalAarFiles
:deleteJavaDir UP-TO-DATE
:ensureMetadataOutDir UP-TO-DATE
:collectAllJars
:isMetadataGenerationNecessary
:buildMetadata
Skip android.support.v7.internal.view.WindowCallbackWrapper
        Error: android/view/SearchEvent
Skip android.support.v7.internal.view.WindowCallbackWrapper
        Error: android/view/SearchEvent
Skip android.support.v7.internal.view.WindowCallbackWrapper
        Error: android/view/SearchEvent
Skip android.support.v7.internal.view.WindowCallbackWrapper
        Error: android/view/SearchEvent
Skip android.support.v4.hardware.fingerprint.FingerprintManagerCompatApi23
        Error: android/hardware/fingerprint/FingerprintManager$AuthenticationCallback
Skip android.support.v4.hardware.fingerprint.FingerprintManagerCompatApi23$1
        Error: android/hardware/fingerprint/FingerprintManager$AuthenticationCallback
Skip android.support.v7.internal.view.WindowCallbackWrapper
        Error: android/view/SearchEvent
Skip android.support.v4.hardware.fingerprint.FingerprintManagerCompatApi23
        Error: android/hardware/fingerprint/FingerprintManager$AuthenticationCallback
Skip android.support.v4.hardware.fingerprint.FingerprintManagerCompatApi23$1
        Error: android/hardware/fingerprint/FingerprintManager$AuthenticationCallback
Skip android.support.v7.internal.view.WindowCallbackWrapper
        Error: android/view/SearchEvent
Skip android.support.v4.hardware.fingerprint.FingerprintManagerCompatApi23
        Error: android/hardware/fingerprint/FingerprintManager$AuthenticationCallback
Skip android.support.v4.hardware.fingerprint.FingerprintManagerCompatApi23$1
        Error: android/hardware/fingerprint/FingerprintManager$AuthenticationCallback
Skip android.support.v7.internal.view.WindowCallbackWrapper
        Error: android/view/SearchEvent
Skip android.support.v4.hardware.fingerprint.FingerprintManagerCompatApi23
        Error: android/hardware/fingerprint/FingerprintManager$AuthenticationCallback
Skip android.support.v4.hardware.fingerprint.FingerprintManagerCompatApi23$1
        Error: android/hardware/fingerprint/FingerprintManager$AuthenticationCallback
Skip android.support.v7.internal.view.WindowCallbackWrapper
        Error: android/view/SearchEvent
Skip android.support.v4.hardware.fingerprint.FingerprintManagerCompatApi23
        Error: android/hardware/fingerprint/FingerprintManager$AuthenticationCallback
Skip android.support.v4.hardware.fingerprint.FingerprintManagerCompatApi23$1
        Error: android/hardware/fingerprint/FingerprintManager$AuthenticationCallback
Skip com.telerik.android.primitives.widget.sidedrawer.BlurFadeLayer
        Error: Landroid/support/v8/renderscript/RenderScript;
:copyMetadata
:generateNativescript-telerik-uiDebugAssets UP-TO-DATE
:mergeNativescript-telerik-uiDebugAssets
:generateNativescript-telerik-uiDebugResValues
:generateNativescript-telerik-uiDebugResources
:mergeNativescript-telerik-uiDebugResources
:processNativescript-telerik-uiDebugManifest
:processNativescript-telerik-uiDebugResources
C:\Users\XXX\Documents\Perso\Dev\XXX\platforms\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.1.0\res\values-v23\values-v23.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
C:\Users\XXX\Documents\Perso\Dev\XXX\platforms\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.1.0\res\values-v23\values-v23.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

:processNativescript-telerik-uiDebugResources FAILED

FAILURE: Build failed with an exception.
</pre>

* On 'tns livesync android --watch' (when i try to display the screen containing the RadListView) :
<pre>
Error: cannot create module /data/data/org.nativescript.XX/files/app/tns_modules/nativescript-telerik-ui/listview.
TypeError: Cannont read porperty 'widget' of undefined.
</pre>

* Windows 10
* TNS 1.5.1
* Nativescript Telerik UI 0.1.3

Regards,
Guillaume

**Comment by JanineGarrett** [comment]
Hi - I'm also having the same problem  Sample apps work until I add telerik-nativescript-ui mdoule, then fails with same error.  I've also tried using the latest build from NativescriptRocks, with same result.

Using Windows 8.1, and also TNS 1.5.1 and Nativescript Telerik UI 0.1.3.

Cheers
Janine

**Comment by ginev** [comment]
Hi @JanineGarrett and @guillaume-roy,
can you please try opening the node_modules/nativescript-telerik-ui/platforms/android/include.gradle file and editing it as follows:

```
android {
	productFlavors {
		"nativescript-telerik-ui" {
			dimension "nativescript-telerik-ui"
		}
	}
}

dependencies {
	compile "com.android.support:appcompat-v7:$suppotVer"
	compile "com.android.support:recyclerview-v7:$suppotVer"
}
```

This should resolve the issue.
Please clean rebuild your apps after that.

**Comment by guillaume-roy** [comment]
Hi @ginev,

With your modification, i have now a new error at 'tns build android' :
<pre>
c:\Users\XX\Documents\Perso\Dev\XX>tns build android
Executing before-prepare hook from c:\Users\XX\Documents\Perso\Dev\XX\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 1.7.3
Successfully prepared plugin nativescript-telerik-ui for android.
Project successfully prepared

:config phase:  createDefaultIncludeFiles
        +found plugins: nativescript-telerik-ui

:config phase:  createPluginsConfigFile
        +creating product flavors include.gradle file in configurations folder...

:config phase:  pluginExtend
        +applying configuration from: C:\Users\XX\Documents\Perso\Dev\XX\platforms\android\configurations\include.gradle
        +applying configuration from: C:\Users\XX\Documents\Perso\Dev\XX\platforms\android\configurations\nativescript-telerik-ui\include.gradle

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\XX\Documents\Perso\Dev\XX\platforms\android\configurations\nativescript-telerik-ui\include.gradle' line: 10

* What went wrong:
A problem occurred evaluating script.
> Could not find property 'suppotVer' on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@c7f4457.
</pre>

Here is my node_modules/nativescript-telerik-ui/platforms/android/include.gradle content before your modification :
<pre>
android {
	productFlavors {
		"nativescript-telerik-ui" {
			dimension "nativescript-telerik-ui"
		}
	}
}

dependencies {
	compile "com.android.support:appcompat-v7:23.1.0"
	compile "com.android.support:recyclerview-v7:23.1.0"
}
</pre>

Thanks.

**Comment by ginev** [comment]
Hello @guillaume-roy ,

After a short discussion with my colleagues we came to the conclusion that the right approach is to keep the hardcoded version of the support library in the include.gradle file. Since the plugin has been designed to work with that version, it is not recommended to obtain the version of the support library by using the `$suppotVer` approach. So, you will need to install the 23.1.0 support library via your Android SDK manager to be able to build and run the solution. Can you try this approach and let me know if it works for you?

**Comment by guillaume-roy** [comment]
Hello @ginev ,

After the update of Android SDK to 23.1.0 it's now working.

Thank you.
