### ISSUE TITLE
Style background of RadListView refresh loader on iOS

### ISSUE THREAD

**Issue by maknz** [telerik/nativescript-ui-samples#46]
Is it possible to change the background of the pull to refresh loader from white?

![screen shot 2015-12-17 at 11 15 16 am](https://cloud.githubusercontent.com/assets/992356/11855563/e05ab5d8-a4af-11e5-8332-6eb08aed0db4.png)

Ideally we'd like that white background behind the loader to be the same as the list, which is `#EEEEEE`. The problem doesn't exist on Android as the loader is overlayed.

v0.1.3

**Comment by ginev** [comment]
You can do this by setting directly the color you want to the native component. Here's a snippet:

` this.listView.ios.pullToRefreshView.backgroundColor = (new colorModule.Color("White")).ios;`

I hope this helps.
