### ISSUE TITLE
RadListView - ScrollToIndex doesn't always repaint correctly

### ISSUE THREAD

**Issue by stonecourier** [telerik/nativescript-ui-samples#48]
If you have a RadListView and use the grid option to display a series of images, and then use the ScrollToIndex method, sometimes it doesn't repaint all the images correctly.

See the screenshot attached, I can use the letters on the right to jump to the correct position in the RadListView but it sometimes does not draw all the images. 

![screenshot_2015-12-27-14-49-54](https://cloud.githubusercontent.com/assets/2016796/12008792/b9681c74-acaa-11e5-8b96-01e4dcf68c6f.png)

**Comment by ginev** [comment]
Thanks @stonecourier for reporting this. This will be investigated and eventually fixed.
