### ISSUE TITLE
RadListView doesn't stack buttons correctly

### ISSUE THREAD

**Issue by stevetayloruk** [telerik/nativescript-ui-samples#49]
Hi,

When using a standing ListView with a StackLayout with two labels and one button it works fine. When replacing with the latest RadListView the button doesn't seem to stack correctly.

Here is both examples:

```
<ListView items="{{ tempData }}" >
            <ListView.itemTemplate>
                <StackLayout orientation="vertical">
                    <Label fontSize="20" height="20" text="{{ headline }}"/>

                    <Label fontSize="14" height="20" text="{{ name }}"/>
                    <Button width="480" height="20" tap="{{ share }}" text="{{ name }}" style="color:black;background-color:red" />
                </StackLayout>
            </ListView.itemTemplate>
        </ListView>
```

and the RadListView not working properly

```
<lv:RadListView id="activityList" items="{{ tempData }}" selectionBehavior="None" style="background-color:transparent">
                <lv:RadListView.listViewLayout>
                    <lv:ListViewLinearLayout scrollDirection="Vertical" itemInsertAnimation="Fade" itemDeleteAnimation="Fade" />
                </lv:RadListView.listViewLayout>
                <lv:RadListView.itemTemplate>
                    <StackLayout>
                        <Label fontSize="14" text="{{ headline }}"/>
                        <Label fontSize="12" text="{{ name }}"/>
                        <Button width="480" tap="{{ share }}" text="{{ name }}" style="color:black;" />
                    </StackLayout>
                </lv:RadListView.itemTemplate>
            </lv:RadListView>
```

any ideas?

thanks

Steve

**Comment by ginev** [comment]
Hello Steve,

Thanks for the code snippet. Is this happening on Android or iOS or both?

**Comment by stevetayloruk** [comment]
Not sure. Only testing on iOS.

**Comment by stevetayloruk** [comment]
FYI - I've also tried replacing the StackLayout with a GridLayout and the buttons don't respect the rows.

```
<lv:RadListView id="activityList" items="{{ tempData }}"  selectionBehavior="None" style="background-color:transparent">
            <lv:RadListView.listViewLayout>
                <lv:ListViewLinearLayout scrollDirection="Vertical" itemHeight="100" itemInsertAnimation="Fade" itemDeleteAnimation="Fade" />
            </lv:RadListView.listViewLayout>
            <lv:RadListView.itemTemplate>
                <GridLayout rows="auto,auto,auto,*">
                    <Label row="1" fontSize="14" text="{{ headline }}"/>
                    <Label row="2" fontSize="12" text="{{ name }}"/>
                    <Button row="3" width="180" height="30" tap="{{ share }}" text="{{ name }}" style="background-color:red;color:black;" />
                </GridLayout>
            </lv:RadListView.itemTemplate>
        </lv:RadListView>

**Comment by ginev** [comment]
Hi @stevetayloruk 
I have tried to reproduce the issue on my side without success. Could you please explain how exactly are you expecting the ListView to behave?
I see that you have explicitly defined height for the ListView items and the Button itself. This will prevent the layout system from automatically calculating the correct sizes. Can you remove these settings and see if it will work as expected?

**Comment by stevetayloruk** [comment]
Hi @ginev,

No, still no luck. I added in the heights afterwards to see if that was the issue. The other thing that might be a consideration is that it's a within a tabview and i've abstracted it out as a UI widget.

```
<TabViewItem title="Activity" iconSource="res://list" xmlns:lv="nativescript-telerik-ui/listview" >
    <TabViewItem.view>
       <lv:RadListView id="activityList" items="{{ activityFeed }}"  selectionBehavior="None" style="background-color:transparent">
            <lv:RadListView.listViewLayout>
                <lv:ListViewLinearLayout scrollDirection="Vertical" itemInsertAnimation="Fade" itemDeleteAnimation="Fade" />
            </lv:RadListView.listViewLayout>
            <lv:RadListView.itemTemplate>
                <GridLayout rows="auto,auto,auto,*" columns="auto,auto">
                    <Label row="1" col="0" fontSize="14" text="{{ headline }}"/>
                    <Label row="2" col="1" fontSize="12" text="{{ name }}"/>
                    <Button row="3" col="0" tap="{{ share }}" text="{{ name }}" style="background-color:red;color:black;" />
                </GridLayout>
            </lv:RadListView.itemTemplate>
        </lv:RadListView>
    </TabViewItem.view>
</TabViewItem>
```

![screen shot 2016-01-11 at 09 11 21](https://cloud.githubusercontent.com/assets/5065543/12229905/dd5bf71e-b843-11e5-9519-7200fe1de2d3.png)

**Comment by stevetayloruk** [comment]
there is also two warnings im getting in the console:

CONSOLE WARN file:///app/tns_modules/nativescript-telerik-ui/listview/listview.js:344:14: The TypeScript constructor "TKListViewDataSourceImpl" will not be executed.

 CONSOLE WARN file:///app/tns_modules/nativescript-telerik-ui/listview/listview.js:383:14: The TypeScript constructor "ExtendedListViewCell" will not be executed.

**Comment by ginev** [comment]
Hello @stevetayloruk,
This is what I am seeing using the latest version of NativeScript and the Telerik UI plugin:

![screen shot 2016-01-11 at 3 05 06 pm](https://cloud.githubusercontent.com/assets/5871176/12234311/c939c67c-b874-11e5-9290-4d7d0159e094.png)

This is your code directly copied into my app. I am using different business objects to feed the list but this should not be related.

**Comment by stevetayloruk** [comment]
very strange. I've done it via a repeater now but I'm at a loss why it's different. The only other thing I could have thought of was global CSS but I've checked this.

**Comment by ginev** [comment]
Can you try zipping the project you're reproducing this with and send it to me for further investigation?

**Comment by stevetayloruk** [comment]
sure, I'll fire it over to you via email if thats ok?

**Comment by ginev** [comment]
Hello @stevetayloruk - yes, go ahead: deyan.ginev@telerik.com

**Comment by stevetayloruk** [comment]
down to an old version.

**Comment by tannt275** [comment]
Hello @ginev . I use RadListView to display item in iOS. But i got this warn
"CONSOLE WARN file:///app/tns_modules/nativescript-telerik-ui/listview/listview.js:370:14: The TypeScript constructor "TKListViewDataSourceImpl" will not be executed."
"ONSOLE WARN file:///app/tns_modules/nativescript-telerik-ui/listview/listview.js:370:14: The TypeScript constructor "TKListViewDataSourceImpl" will not be executed.".
I use nativescript-telerik-ui 1.1.1

**Comment by jalal** [comment]
I'm getting the same problem here. Only in iOS, Android is fine. And the Market place sample works fine, so I'm not sure what is causing this.

**Comment by ginev** [comment]
Hello @jalal and @tannt275,
can you check out the online docs here:
http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/getting-started

Please, follow the getting started guide and let me know how itworks for you.

**Comment by jalal** [comment]
Unless that document has changed recently, then I've been through the process a dozen times.

BTW, why does the first section have:
`xmlns:lv="nativescript-telerik-ui/sidedrawer" for Telerik UI for NativeScript (free)`
as surely that install the sidedrawer, not the listview?

Puzzled....
