### ISSUE TITLE
Calendar selectionMode causes exception

### ISSUE THREAD

**Issue by MiroValchev** [telerik/nativescript-ui-samples#50]
I am using the sample from [here](http://docs.telerik.com/devtools/nativescript-ui/Controls/Calendar/calendar-populating-with-data). It works just fine. However, when I set selectionMode the app crashes (testing in Genymotion)

"Cannot ready property 'setSelectedDates' of undefined
calendar.js, line:223"

<rc:RadCalendar id="calendar"
        eventSource="{{ Source }}"
        height="400" selectionMode="Range"/>

**Comment by NikolayVasilev** [comment]
Hi Miro,

I tested the scenario and everything works as expected. 

adding console.log(e.object.android); in the click handler outputs the expected android calendar type. 

Note that when using the android property you have to access all members with the respective android API signature.

Let me know if there is anything specific that I have to do in order to observe the problem.

**Comment by MiroValchev** [comment]
[nativescript-ui-samples-master-miro-bug.zip](https://github.com/telerik/nativescript-ui-samples/files/94270/nativescript-ui-samples-master-miro-bug.zip)

Hi Niki,

I've uploaded a modified version of your samples. (have removed nativescript-telerik-ui in tns_modules due to its size).

Changes are as follows:
1. selection-modes-model.ts
public selectedDays: Array<Date> = [];
    public selectedRange: calendarModule.DateRange = new calendarModule.DateRange();

    public setSelectionMode(selectionMode: string) {
        this.selectionMode = selectionMode;
        console.log("Days");
        console.log(JSON.stringify(this.selectedDays));
        console.log("Range");
        console.log(JSON.stringify(this.selectedRange));
    }

2. selection-modes.ts
import viewModel = require("./selection-modes-model");
import calendarModule = require("nativescript-telerik-ui/calendar");
import view = require("ui/core/view");

var viewModelContext : viewModel.ViewModel;

export function onPageLoaded(args){
    var page = args.object;
    viewModelContext = new viewModel.ViewModel();
    page.bindingContext = viewModelContext;
	
	
    var cal = view.getViewById(page, "calendar");
}

3. selection-modes.xml
        <rc:RadCalendar id="calendar" 
			selectionMode="{{ SelectionMode }}"
			selectedDateRange="{{ selectedRange }}"
            selectedDates="{{ sectedDays }}"
			row="1"
			height="400"/>

Tested both in Genymotion and Moto G 2015 (5.1.1)

If I try cal.android the debugger crashes.

As for the binding, after playing around both with Multiple and Range modes, the binding props are still empty - selectedDays and selectedRange. 

Is it just me doing sth really stupid or these are real bugs?

Cheers,
Miro

**Comment by MiroValchev** [comment]
![bug2](https://cloud.githubusercontent.com/assets/7013750/12392154/82a7ac98-bdf5-11e5-9601-b25b54446e7f.png)

This is another thing that I've noticed. Multiple selection mode. As you can see there are three selected days, yet e.object.SelectedDays is empty?

<rc:RadCalendar id="calendar"
                      eventSource="{{ Source }}"
                      dateSelected="{{ click }}"
                      selectionMode="{{ selectionMode }}"                      
                      />

**Comment by NikolayVasilev** [comment]
Hi Miro,

The binding issue, certainly looks like a bug, and I will investigate it.
As to the undefined android property, I still cannot reproduce the issue on
my side. Can you share the exact code you are trying to execute that
results in the exception?

Thank you in advance.

**Comment by MiroValchev** [comment]
Hi Niki,

The code is included in the attached zip file.

I have also mentioned it above:

export function onPageLoaded(args){
var page = args.object;
viewModelContext = new viewModel.ViewModel();
page.bindingContext = viewModelContext;

var cal = view.getViewById(page, "calendar");
}

You can set a brk point on after var cal and you will see that cal.android is undefined.

**Comment by NikolayVasilev** [comment]
Hi Miro,

The android reference, a.k.a. the native instance wrapper is instantiated a bit later than the initial load. That i s why you see it as undefined in the PageLoaded handler. If you add a click handler, you will see that the android reference is set correctly. 

Hope this helps.

**Comment by MiroValchev** [comment]
Hi Niki,

Just tried what you've suggested - tap event in the view. Again the app crashed when evaluating cal.android.

The screenshot above is from the method handling the tap event in the view model. Again cal.android was undefined.

Can't you reproduce it in the example that I've sent?

If you need more info ping me at miro@thecoolapps.com and we can exchange skype contacts.

**Comment by MiroValchev** [comment]
![nasty debugger bug](https://cloud.githubusercontent.com/assets/7013750/12450390/2c509dc6-bf8c-11e5-8bd5-d63252482594.png)

Hope this helps. Happens both on device and emulator. I am pretty sure it's a pure debugger issue. For example console.log(cal.android) in a tap event would not crash the app. However if you try to do anything in the debugger console it would crash. This makes development and diagnosing issues harder, but at least the would work.

**Comment by NikolayVasilev** [comment]
Yes, so far the only problem is in debug mode, when trying to observe the android property. 

We are working on what the exact problem is. I will post an update when we have more information on the matter.
