### ISSUE TITLE
SideDrawer: Is there a way to disable the swipe-to-open behaviour?

### ISSUE THREAD

**Issue by dragGH102** [telerik/nativescript-ui-samples#53]
I only want to programmatically open/close the menu (following tap events on buttons), **is there a way to disable swipe-to-show-drawer behaviour**?
In this repo I found this snippet (file: sidedrawer/transitions/drawer-transitions.js)

    if (frame.topmost().ios) {
        frame.topmost().ios.controller.interactivePopGestureRecognizer.enabled = false;
    }

which apparently serves to achieve this on ios (not sure, can't test on ios as I'm developing on Android without a Mac temporarily).
However, how to achieve this on **android**?

Thanks in advance

**Comment by ginev** [comment]
Hello @dragGH102, 

Yes, you can do this on Android via the `setIsLocked` method:

`drawer.android.setIsLocked(true);`

This will make the drawer unaware of the gestures but you can still use the dedicated methods to open or close it.

**Comment by dragGH102** [comment]
thanks @ginev 

btw,  since you seem to have a good knowledge on nativescript-telerik-ui, do you have any idea why I get into this other issue? (https://github.com/telerik/nativescript-ui-samples/issues/52)

i will close this one

**Comment by guliashki** [comment]
Hello @dragGH102 ,

The way to disable showing/hiding the drawer with gesture on iOS is by setting the <code>allowGestures</code> property:
<code>
drawer.ios.defaultSideDrawer.allowGestures = false;
</code>

**Comment by dragGH102** [comment]
@guliashki thanks a lot

**Comment by ginev** [comment]
@dragGH102 we're going to expose a common property through the SideDrawer wrapper for this.

**Comment by dragGH102** [comment]
@ginev I just upgraded to {N} 1.6.0.

The following code **used to work in 1.5.2** but on 1.6.0 it doesn't.

Tested on **Android**.
**Error: sideDrawer.android is not defined**

Also, any news on the official support for "disable drag to show drawer" behavior?

**Code** (note: I replaced frameModule.topmost() with global. but in both cases same issue)

 ```
      var sideDrawer: drawerModule.RadSideDrawer = <drawerModule.RadSideDrawer>frameModule.topmost().getViewById("sidedrawer");

        // android
        if (global.android) sideDrawer.android.setIsLocked(true);
        // ios
        if (global.ios) sideDrawer.ios.defaultSideDrawer.allowGestures = false;
```

**Comment by ginev** [comment]
@dragGH102 ,
We're going to take a look at this. Where's the place where you are calling this code?
The official support for locking the drawer is going to be available in the next version of the package we're going to upload. Probably in a week time-frame.

**Comment by dragGH102** [comment]
@ginev the function itself is defined in a model "sidedrawer" (very similarly to how it's done in nativescript-ui-samples). then a global.setDrawerProperties is defined, calling a method of the model "sidedrawer". Finally this global method is called in **loaded** event of one of my views (pages).

An almost-the-same example is https://github.com/dragGH102/nativescript-sample-app-with-menu

**Comment by ginev** [comment]
@dragGH102 the problem is that the Core Modules behavior was changed in the latest release of NS and the `android` property is not available in the `loaded` event. You should be using the `navigatedTo` method to execute this logic.

**Comment by dragGH102** [comment]
@ginev thank you. is this supposed to fix also the

     cannot set property ..

@ https://github.com/telerik/nativescript-ui-samples/issues/66 

?

**Comment by ginev** [comment]
Yes. Let me know if the problem persists.

**Comment by dragGH102** [comment]
@ginev thanks. looks working for now. is any issue will arise I'll reopen the issue

**Comment by IvRRimum** [comment]
What's the solution for {N} + angular2 ?

```
 67   @ViewChild(RadSideDrawerComponent) public drawerComponent: RadSideDrawerComponent;
 68   private drawer: SideDrawerType;
 69 
 70   ngAfterViewInit() {
 71     this.drawer = this.drawerComponent.sideDrawer;
 72     this._changeDetectionRef.detectChanges();
```

**Comment by IvRRimum** [comment]
Also how can i set height and width for the tkDrawerContent?

**Comment by VladimirAmiorkov** [comment]
Hi @IvRRimum ,

By design the `tkDrawerContent` inline directive can be placed on any `View` element in your {N} + Angular 2 application, by definition you can easily change the size of those views by setting their height and/or width. For example here is how you would set those properties to 200 and 100 when using with RadSideDrawer's drawer content:

```
<RadSideDrawer>
    <StackLayout tkDrawerContent height="200" width="100">
        <StackLayout>
            <Label text="Navigation Menu"></Label>
        </StackLayout>
        <StackLayout>
            <Label text="Primary"></Label>
            <Label text="Social"></Label>
            <Label text="Promotions"></Label>
            <Label text="Labels"></Label>
            <Label text="Important"></Label>
            <Label text="Starred"></Label>
            <Label text="Sent Mail"></Label>
            <Label text="Drafts"></Label>
        </StackLayout>
    </StackLayout>
    <StackLayout tkMainContent>
        <Label text="mainContent Text" textWrap="true"></Label>
    </StackLayout>
</RadSideDrawer>  
```
