### ISSUE TITLE
SideDrawer crash on iOS

### ISSUE THREAD

**Issue by aylesm** [telerik/nativescript-ui-samples#54]
Using version 0.2.3 when I add a basic sidedrawer to a page the app crashes with a segmentation fault.  Please help.

**Comment by NikolayVasilev** [comment]
Hi, 

Would it be possible to provide a bit more information on the case? What is the {N} runtime version you are using? Are you getting the error when starting the app, or when trying to show the drawer? How is the SifeDrawer placed inside the page's XML? 

Thank you in advance.

**Comment by ginev** [comment]
@aylesm closing this issue as there's no further input from you. Feel free to reopen it if needed.

**Comment by aylesm** [comment]
@ginev, sorry close it.  I tried adding the sidedrawer menu to the groceries sample and there is some issues with that.  Using the menu on a clean project works like a dream.
