### ISSUE TITLE
RadListView is choppy on iOS

### ISSUE THREAD

**Issue by enchev** [telerik/nativescript-ui-samples#58]
_From @Ivshti on February 5, 2016 14:41_

First of all, I don't know if this is the right repo, and second - there's no more technical detail/information about my issue that I can provide.

The issue is that the RadListView is noticeably choppy on iOS compared to Android when scrolling (kinetic scroll). This happens on emulator AND a real 5s device, with the Examples app (Item Layouts) and on emulator (iPhone 6s) and my own application.

The "choppyness" is essentially non-smooth scrolling - once the scrolling is started it slows down periodically a few times a second in a symmetrical (periodic) way.  

_Copied from original issue: NativeScript/NativeScript#1504_

**Comment by enchev** [comment]
_From @ginev on February 5, 2016 16:18_

Hello @Ivshti ,

We are aware of this behavior and are actively working on resolving the issue so stay tuned for updates.

When it comes to the UI suite, it is best to comment in the dedicated repo: https://github.com/telerik/nativescript-ui-samples/issues

Thanks!

**Comment by enchev** [comment]
_From @Ivshti on February 5, 2016 16:21_

@ginev thanks for the update

Primarily reason we use RadListView is because of the load on demand - to avoid memory issues on Android. Considering iOS is ran on powerful devices, can we use ListView with a Wrap/Grid layout template in place of the RadListView as a workaround?

**Comment by ginev** [comment]
@enchev thanks for moving the issue here. 

A quick update on the case: We have identified some potential reasons for the choppyness and are currently working on validating and addressing them.

**Comment by imaginationcoder** [comment]
any update on this?. I am also getting the same behaviour in iOS when used RadListView 'LoadOnDemand' and in Android scrolling is smooth.
Can anyone please give me a quick reply?
