### ISSUE TITLE
Calendar maxDate cannot be removed once set

### ISSUE THREAD

**Issue by MiroValchev** [telerik/nativescript-ui-samples#59]
Hi guys, I believe this code should result in no limitations for date selection:
```
vm.cal = view.getViewById(page, "calendar");     
vm.cal.maxDate = new Date();
vm.cal.maxDate = 0;
```

However, setting maxDate back to 0 has no effect?

**Comment by guliashki** [comment]
@MiroValchev Indeed setting maxDate to 0 or undefined has no effect. The issue will be addressed in the next public release of telerik-ui package.

**Comment by MiroValchev** [comment]
Thanks @guliashki
