### ISSUE TITLE
Setting properties for CategoryAxis

### ISSUE THREAD

**Issue by nguyenbn** [telerik/nativescript-ui-samples#6]
When I try to set the properties of the CategoryAxis, it doesn't appear to do anything.  Maybe I'm setting it incorrectly:

This code:
```
<chart:CategoricalAxis PlotMode="OnTicks" MajorTickInterval="2" GapLength="1" LabelTextColor="#F00" />
```
renders the same as
```
<chart:CategoricalAxis />
```

**Comment by karaahmed** [comment]
Hi nguyenbn,

The attribute names in xml description should be in camel case beginning with lower case letter as follows:
```
<chart:CategoricalAxis plotMode="OnTicks" majorTickInterval="2" gapLength="1" labelTextColor="#F00" />
```
For further details you can check our documentation : http://docs.telerik.com/devtools/nativescript-ui/

Hope this helps. Feel free to contact us in case you have any problems or concerns.

Regards,
Bulent

**Comment by nguyenbn** [comment]
Hi Bulent,

Thanks for your quick response.  That definitely did the trick!  

Best,
Bao
