### ISSUE TITLE
Unable to use RadListView

### ISSUE THREAD

**Issue by tilutza** [telerik/nativescript-ui-samples#60]
Hi,

I downloaded the sample task project and I've tried to create a new page:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd"
      xmlns:lv="nativescript-telerik-ui/listview"
      xmlns:common="components/common"
      navigatingTo="navigatingTo">
  <GridLayout>
    <Button text="load" tap="loadItemsTap" cssClass="primaryButton" />
    <lv:RadListView items="{{ items }}" itemTap="itemTap">
      <lv:RadListView.itemTemplate>
        <StackLayout orientation="vertical">
          <Label text="{{ name }}" style="font-weight: bold; font-size: 30" />
          <Image src="{{ thumbnail }}" stretch="none" style="horizontal-align: center; height: 250" />
        </StackLayout>
       </lv:RadListView.itemTemplate>
    </lv:RadListView>

    <ActivityIndicator busy="{{ isLoading }}" />
  </GridLayout>
</Page>
```

I added the nativescript UI plugin and followed the guide for RadListView
The build is ok, but when I run the project I get the following error:
http://imgur.com/Q8WpYem

I think something is missing from the plugin dependancy or the guide is not complete.

Also, I see the chart is not free but the RadListView is it free ?

Thanks,
Daniel

**Comment by ginev** [comment]
Hello @tilutza ,

Based on what I am seeing in the stack trace I think NativeScript cannot resolve the native libraries containing the controls. Can you please share some more details on what steps exactly did you take? This will help me reproduce the scenario on my side and see how I can help you.

**Comment by ginev** [comment]
@tilutza, any progress on this?

**Comment by tilutza** [comment]
Hi,


Meanwile I switched to otheer topic. However what I did is to download the samplesTask TypeScript project and to follow the RadListView toturial (adding the plugin).

I don't have time right now to reproduce again, but I will do it next week.
Thank you for your understanding.

Regards,
Daniel

**Comment by ginev** [comment]
@tilutza ,
here's a quick tip to experiment: try deleting the node_modules folder in your project and running it again. this should resolve the issue.
