### ISSUE TITLE
Hide Horizontal Axis from Chart Bar Series

### ISSUE THREAD

**Issue by lrsaturnino** [telerik/nativescript-ui-samples#61]
Hi, I'm trying to hide the Horizontal Axis from a chart bar series, but I'm not sure on how to do it and didn't find any help on documentation. Any clues?

**Comment by karaahmed** [comment]
There is not an exposed property to hide the axis from xml or using axis JS instance. 
But there is a way to do this accessing the native instance as follows:
for iOS: 
 `    axis.ios.hidden = true;`
for Android:
`     axis.android.setVisible(false);`

The "hidden" property will be introduced with next public release of telerik-ui package.
