### ISSUE TITLE
Cannot build nativescript-ui-samples w/ tsc (TypeScript)

### ISSUE THREAD

**Issue by lelong37** [telerik/nativescript-ui-samples#64]
We're not able to build the sample project with TypeScript? Please help...

![2016-02-17_14-17-57](https://cloud.githubusercontent.com/assets/4691404/13126906/6db43218-d581-11e5-89e1-6dc2fd8529d4.png)

**Comment by ginev** [comment]
@lelong37 ,

Could you please post some more details on the steps you are taking so that I can try to reproduce this here and be able to help?

**Comment by lelong37** [comment]
Sure @ginev: 

- Cloned latest from your (this) master branch
- We're running Node 4.2.1, TypeScript 1.7.5
- npm install (get all npm dependencies)
- tsc (from the root of ./sdk/app, where we see the tsconfig.json)
- after failed build, we attempted to fix tsconfig.json for things that are no longer supported in TS 1.7.5, still have build errors

**Comment by ginev** [comment]
Hello @lelong37 ,

Please make sure you are using the `release` branch of this repository. It is set as the default branch and you should be using it. The master branch is used for development purposes.

Also, make sure you are using the 0.2.4 version of the `nativescript-telerik-ui` plugin.
