### ISSUE TITLE
does support nativescript 1.6.0?

### ISSUE THREAD

**Issue by wenhsiaoyi** [telerik/nativescript-ui-samples#65]
I can not use on nativescript 1.6.0.
But run normal for 1.5.2
does ui modules support nativescript 1.6.0?

**Comment by ginev** [comment]
Hello @wenhsiaoyi ,
we are going to publish an update of NS UI that supports 1.6.0 very soon.

**Comment by ginev** [comment]
Hello @wenhsiaoyi ,

I've just tested the Samples app with 1.6 and did not experience any issues with it. Could you please share some more details on your case so that I can make sure that I correctly reproduce it on my side?

**Comment by Adavo** [comment]
Successfully prepared plugin nativescript-telerik-ui for android.
Successfully prepared plugin tns-core-modules for android.
Project successfully prepared

:config phase:  createDefaultIncludeFiles
        +found plugins: nativescript-telerik-ui

:config phase:  createPluginsConfigFile
        +creating product flavors include.gradle file in configurations folder...

:config phase:  pluginExtend
        +applying configuration from: C:\Workspace\NativeScript\nativescript-ui-samples\sdk\platforms\android\configurations\include.gradle
        +applying configuration from: C:\Workspace\NativeScript\nativescript-ui-samples\sdk\platforms\android\configurations\nativescript-telerik-ui\include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
        +adding dependency: C:\Workspace\NativeScript\nativescript-ui-samples\sdk\platforms\android\libs\aar\Chart-2015.3.1307-trial-release.aar
        +adding dependency: C:\Workspace\NativeScript\nativescript-ui-samples\sdk\platforms\android\libs\aar\Common-2015.3.1307-trial-release.aar
        +adding dependency: C:\Workspace\NativeScript\nativescript-ui-samples\sdk\platforms\android\libs\aar\Data-2015.3.1307-trial-release.aar
        +adding dependency: C:\Workspace\NativeScript\nativescript-ui-samples\sdk\platforms\android\libs\aar\Input-2015.3.1307-trial-release.aar
        +adding dependency: C:\Workspace\NativeScript\nativescript-ui-samples\sdk\platforms\android\libs\aar\List-2015.3.1307-trial-release.aar
        +adding dependency: C:\Workspace\NativeScript\nativescript-ui-samples\sdk\platforms\android\libs\aar\Primitives-2015.3.1307-trial-release.aar
        +adding dependency: C:\Workspace\NativeScript\nativescript-ui-samples\sdk\platforms\android\libs\aar\widgets-release.aar

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'sdk'.
> Could not resolve all dependencies for configuration ':_nativescript-telerik-uiDebugCompile'.
   > Could not find com.android.support:appcompat-v7:23.1.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.jar
         file:/C:/Workspace/NativeScript/nativescript-ui-samples/sdk/platforms/android/libs/aar/appcompat-v7-23.1.0.jar
         file:/C:/Workspace/NativeScript/nativescript-ui-samples/sdk/platforms/android/libs/aar/appcompat-v7.jar
         file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.pom
         file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.jar
     Required by:
         :sdk:unspecified
   > Could not find com.android.support:appcompat-v7:23.1.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.jar
         file:/C:/Workspace/NativeScript/nativescript-ui-samples/sdk/platforms/android/libs/aar/appcompat-v7-23.1.0.jar
         file:/C:/Workspace/NativeScript/nativescript-ui-samples/sdk/platforms/android/libs/aar/appcompat-v7.jar
         file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.pom
         file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.jar
     Required by:
         :sdk:unspecified
   > Could not find com.android.support:recyclerview-v7:23.1.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/23.1.0/recyclerview-v7-23.1.0.pom
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/23.1.0/recyclerview-v7-23.1.0.jar
         file:/C:/Workspace/NativeScript/nativescript-ui-samples/sdk/platforms/android/libs/aar/recyclerview-v7-23.1.0.jar
         file:/C:/Workspace/NativeScript/nativescript-ui-samples/sdk/platforms/android/libs/aar/recyclerview-v7.jar
         file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/android/support/recyclerview-v7/23.1.0/recyclerview-v7-23.1.0.pom
         file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/com/android/support/recyclerview-v7/23.1.0/recyclerview-v7-23.1.0.jar
     Required by:
         :sdk:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 17.844 secs
Command C:\Workspace\NativeScript\nativescript-ui-samples\sdk\platforms\android\gradlew.bat failed with exit code 1
# run android
┌────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Usage                                                  │ Synopsis                                                                                                                                                                                                   │
│ Run on all connected devices and running emulators     │ $ tns run android [--key-store-path <File Path> --key-store-password <Password> --key-store-alias <Name> --key-store-alias-password <Password>] [--release] [--justlaunch]                                 │
│ Run on a selected connected device or running emulator │ $ tns run android --device <Device ID> [--key-store-path <File Path> --key-store-password <Password> --key-store-alias <Name> --key-store-alias-password <Password>] [--release] [--justlaunch]            │
│ Start an emulator and run the app inside it            │ $ tns run android --emulator [<Emulator Options>] [--key-store-path <File Path> --key-store-password <Password> --key-store-alias <Name> --key-store-alias-password <Password>] [--release] [--justlaunch] │
└────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

Runs your project on a connected Android device or in a native Android emulator, if configured. This is shorthand for prepare, build and deploy. While your app is running, prints the output from the application in the console.

### Options

    * --device - Specifies a connected device on which to run the app.
    * --emulator - If set, runs the app in a native emulator for the target platform, if configured. When set, you can also set any other valid combination of emulator options as listed by $ tns help emulate android.
    * --release - If set, produces a release build. Otherwise, produces a debug build. When set, you must also specify the --key-store-* options.
    * --key-store-path - Specifies the file path to the keystore file (P12) which you want to use to code sign your APK. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-password - Provides the password for the keystore file specified with --key-store-path. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-alias - Provides the alias for the keystore file specified with --key-store-path. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-alias-password - Provides the password for the alias specified with --key-store-alias-password. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --justlaunch - If set, does not print the application output in the console.

### Attributes

    * <Device ID> is the index or name of the target device as listed by $ tns device android
    * <Emulator Options> is any valid combination of options as listed by $ tns help emulate android

Sending exception report (press Ctrl+C to stop).......

**Comment by wenhsiaoyi** [comment]
I am use Telerik UI for NativeScript on my project.
My project show the error message is "can not load sidedrawer".
In older 1.5.x , After build , I found the folder of Telerik UI for NativeScript is on the root of App.
But in 1.6.x, all node_module are move into the new folder name node_module.
But Telerik UI for NativeScript still in root of app. 
So I replace Nativescript to 1.5.x. It is work.

**Comment by wenhsiaoyi** [comment]
![2016 3 2 08-33-07](https://cloud.githubusercontent.com/assets/185473/13460526/0ff2066a-e0b6-11e5-9e48-d5a8f5051036.png)
I can not get the object of sideDrawer. it is undefined.
But on 1.5.x is normal. Error in 1.6.2.

**Comment by wenhsiaoyi** [comment]
update plugin ui for nativescript 0.2.4
now, it can run normally.
but, i think some cache need to clean.
some code need to change for application start in app. js.
thanks all
