### ISSUE TITLE
RadSideDrawer how to disable the flick gesture

### ISSUE THREAD

**Issue by ljx0517** [telerik/nativescript-ui-samples#68]
how to disable the flick gesture
i just want open the hidden view  by a button ,in my app the default flick gesture has another mean,
sorry for my english
thanks

**Comment by guliashki** [comment]
Hi @ljx0517 ,

You can disable the swipe-to-open drawer behavior by calling `setIsLocked` method in android and setting `allowGestures` property in iOS:
<code>drawer.android.setIsLocked(true);</code>
`drawer.ios.defaultSideDrawer.allowGestures = false;`

A common property through the SideDrawer wrapper will be exposed in our next public release.
