### ISSUE TITLE
Not possible to build an app with the nativescript-telerik-ui plugin installed

### ISSUE THREAD

**Issue by jgsacris** [telerik/nativescript-ui-samples#69]
when building the android app (tns run android) the build process fails with:
`Execution failed for task ':processNativescript-telerik-uiDebugResources'.`

Looking above there is the following message:
`C:\**\platforms\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.1.0\res\values-v23\values
-v23.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
C:\**\platforms\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.1.0\res\values-v23\values
-v23.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.`

Any ideas what this could mean? Is the Android SDK 23 a requirement?

**Comment by ginev** [comment]
Hello @jgsacris you will have to make sure that API Level 23 is installed via the Android SDK manager.

**Comment by miroslavaivanova** [comment]
If you have any feedback, issues or feature requests please log them in nativescript-ui-feedback repository.

Thanks for your understanding!
