### ISSUE TITLE
sidedrawer.d.ts is not a module

### ISSUE THREAD

**Issue by vdende** [telerik/nativescript-ui-samples#73]
For example, when I open `app/sidedrawer/callbacks/drawer-callbacks-module.ts`, I see the following error in atom:
  `nativescript-telerik-ui/sidedrawer/sidedrawer.d.ts is not a module`

I get the same error when I build a project from scratch:
  `tns create test-sidedrawer-ts --template typescript`
  `cd test-sidedrawer-ts`
  `tns platform add ios`
  `tns plugin add nativescript-telerik-ui`
  In `main-page.ts` add `import { RadSideDrawer } from "nativescript-telerik-ui/sidedrawer”;`

What am I missing?

**Comment by AlexandreKilian** [comment]
same problem with the listview... I'm importing it like in the sample:

> import listViewModule = require("nativescript-telerik-ui/listview");

**Comment by yezarela** [comment]
I had the same problem before, this is what I've done
Modify file `listview.d.ts` in nativescript-telerik-ui directory inside `node_modules` with this
`declare module "nativescript-telerik-ui/listview" `

Also, modify file `package.json` in `nativescript-telerik-ui` directory, with this
`{ "name" : "listview",
  "main" : "listview.js" }`

Hope that works,

**Comment by AlexandreKilian** [comment]
Could you make a pull request with those changes?

**Comment by miroslavaivanova** [comment]
If you have any feedback, issues or feature requests please log them in nativescript-ui-feedback repository.

Thanks for your understanding!
