### ISSUE TITLE
Make default Legend title "Legend" not "Bottom"

### ISSUE THREAD

**Issue by sitefinitysteve** [telerik/nativescript-ui-samples#75]
I don't have "Bottom" in my code at all, not sure where this is coming from?  I appear to be running v0.2.3 w/out the trial popup.

http://www.screencast.com/t/JuuavUm5zq

**Comment by sitefinitysteve** [comment]
Sorry turns out this is the default of the "title", so title="" fixes it (removes it I suppose)

...but "Bottom" as the default legend title instead of "Legend"?

**Comment by karaahmed** [comment]
I should be default value mistake at our side. Will fix it for release. 
Thank you.
