### ISSUE TITLE
RadListView Horizontal scroll

### ISSUE THREAD

**Issue by girishgkg** [telerik/nativescript-ui-samples#76]
Can we disable vertical scroll when user scrolling horizontally ?

**Comment by girishgkg** [comment]
Looks like view bounces when we scroll Radlistview horizontally..

**Comment by ginev** [comment]
Hello @girishgkg ,

This was a bug in RadListView which has been addressed in our codebase and will be part of the upcoming end of March release of Telerik UI.

Thanks!
