### ISSUE TITLE
Android - gradle task buildMetadata failed - R file

### ISSUE THREAD

**Issue by vyscond** [telerik/nativescript-ui-samples#77]
## Issue

Hi i tried to use and build the default native script project "tab button achievement" with `tns run android` but i got this error bellow.

```
Exception in thread "main" java.lang.IllegalArgumentException: Class org.nativescript.mobileinfosae.R conflict: /Users/vyscond/Development/mobile-infosae/platforms/android/build/intermediates/classes/debug and /Users/vyscond/Development/mobile-infosae/platforms/android/build/intermediates/classes/nativescript-telerik-ui/debug
    at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
    at com.telerik.metadata.Builder.build(Builder.java:41)
    at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED
```

the `main-page.xml`

``` xml
<Page loaded="pageLoaded" xmlns:drawer="nativescript-telerik-ui/sidedrawer" xmlns="http://www.nativescript.org/tns.xsd">
  <drawer:RadSideDrawer>
    <drawer:RadSideDrawer.mainContent>
      <StackLayout >
        <Label text="{{ mainContentText }}" textWrap="true"/>
      </StackLayout>
    </drawer:RadSideDrawer.mainContent>
    <drawer:RadSideDrawer.drawerContent>
      <StackLayout cssClass="drawerContent">
        <StackLayout cssClass="headerContent">
          <Label text="Header"/>
        </StackLayout>
        <StackLayout cssClass="drawerMenuContent">
          <Label text="Item 1"/>
          <Label text="Item 2"/>
          <Label text="Item 3"/>
          <Label text="Item 4"/>
        </StackLayout>
      </StackLayout>
    </drawer:RadSideDrawer.drawerContent>
  </drawer:RadSideDrawer>
</Page>
```
## SDK Info
- tns version `1.7.0`
- typescript version `1.8.9`
- package.json 

```
{
  "nativescript": {
    "id": "org.nativescript.mobileinfosae",
    "tns-android": {
      "version": "1.7.0"
    }
  },
  "dependencies": {
    "nativescript-telerik-ui": "^0.2.4",
    "tns-core-modules": "1.7.0"
  }
}
```

**Comment by vyscond** [comment]
It seems that i needed to run the `clean` task from `gradlew` to make it worked. Maybe this can be flagged as possible issue on fresh install?

**Comment by ginev** [comment]
@vyscond,

This isn't something we've stumbled upon and is probably somehow related to your development environment. Let us know if you continue experiencing issues.

**Comment by toddanglin** [comment]
Hit this exact same issue tonight (on Mac with TNS 1.7.0). Seems to be related to adding Telerik UI for NativeScript...possibly adding it after you've already built the {N} Android project without UI for NativeScript causes the problem?

@vyscond's solution worked for me, too. Run `./gradlew clean` in the `platforms` > `android` folder.

**Comment by Headcult** [comment]
@vyscond's solution worked for me, too. Run `gradlew clean` in the `platforms > android` folder.

Thanks a lot!!

**Comment by vyscond** [comment]
@toddanglin described the scenario of the erro flawlessly. I cannot replicate the fix right now (working on other things) but i think we had enough positive feedback using the proposed fix. Feel free to close as solved mates! 

Cheers,

**Comment by Headcult** [comment]
Also, this issue occurs while running 'tns run android' after a new plugin has been installed. Once the gradlew clean is executed, it goes through fine, so, this is a very important step while using plugins in NativeScript.

**Comment by ginev** [comment]
@vyscond @toddanglin reproduced it in pretty much the same way. Adding NS UI after executing tns build android.

**Comment by poorcoder** [comment]
I am getting this info when I run the command as you did...
```./platforms/android/gradlew clean``` => ```Task 'clean' not found in root project```

**Comment by brandon-thimmesch** [comment]
@poorcoder Try navigating into your android folder with the command console, then run `gradlew clean` that should work - at least it did for me. I'm unsure what executing `./platforms/android/gradlew clean` would try and do, but I'm fairly certain typing in `gradlew clean` and omitting `./` will work for you. Let me know if that doesn't work.
