### ISSUE TITLE
SegmentedBar selectedIndex binding does not work after setting new value

### ISSUE THREAD

**Issue by MiroValchev** [telerik/nativescript-ui-samples#79]
Really strange one:

`<SegmentedBar selectedIndexChanged="{{ test1 }}" selectedIndex="{{ selectedDay.sex }}">
            <SegmentedBar.items>
                <SegmentedBarItem title="No" />
                <SegmentedBarItem title="Unprotected" />
                <SegmentedBarItem title="Protected" />
            </SegmentedBar.items>
        </SegmentedBar>`

The first time it works just fine. What I do is bind to the selected day from a calendar component.
//js1
console.log(day.sex);
this.set("selectedDay", day);

`public test1(args: any): void {
//js2
        console.log(args.newIndex + " - " + this.selectedDay.sex);        
    }`

JS1: 1
//tapping the different segmentBarItems
JS2: 1 - 1
JS2: 0 - 0
JS2: 2 - 2

Next I choose a new day.
JS1: 0
JS2: 0 - 0
JS2: 1 - 0
JS2: 2 - 0

As you can see selectedIndex binding is no longer updating the selectedDay.sex value.

**Comment by ginev** [comment]
@MiroValchev can you please specify what component are you using? Is this from nativescript's core modules or from NS UI for NativeScript?

**Comment by MiroValchev** [comment]
@ginev Holy cow, I've posted in the wrong repo :( It's from the core modules, there is no such component in the Telerik UI for {N}. Not sure if we can just change the repo for this issue?

**Comment by ginev** [comment]
You can open a new one and reference this one there.
