### ISSUE TITLE
Set StrokeThickness for LineSeries not working

### ISSUE THREAD

**Issue by Daxito** [telerik/nativescript-ui-samples#80]
I would like to set the StrokeThickness of the line series but is it not working, I set it like this:

< chart:LineSeries **strokeThickness="5"** seriesName="hrsService" 
            items="{{ categoricalSource }}" categoryProperty="Country" valueProperty="Amount">
            </ chart:LineSeries>

Is this not supported? I think it should be.

**Comment by ginev** [comment]
Hello @Daxito , this is done via Palettes: http://docs.telerik.com/devtools/nativescript-ui/Controls/Chart/Styling/Overview

**Comment by Daxito** [comment]
Well, seems like strokeWidth has no effect on a LineSeries

**Comment by ginev** [comment]
@Daxito okay, we will check this out and will get back to you here with more details.

**Comment by Daxito** [comment]
This works great now with version 1.1.1
Thanks!
