### ISSUE TITLE
Android - RadListView runtime error

### ISSUE THREAD

**Issue by na3r** [telerik/nativescript-ui-samples#83]
Hi there,
i'v installed telerik ui according to documentation, i'd like to use RadListView componenet but unfortunately i get following run time error.

tns version: 1.7.0
java version: java version "1.8.0_66"

main.xml

< Page loaded="pageLoaded" xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:lv="nativescript-telerik-ui/listview">
< lv:RadListView>
</ lv:RadListView>
</ Page>

and i have imported nativescript-telerik-ui/listview module in main.js file

The depedency located at /home/na3r/projects/test/node_modules/babel-core/node_modules/lodash with version  3.10.1 will be replaced with dependency located at /home/na3r/projects/test/node_modules/lodash with version 4.6.1
The depedency located at /home/na3r/projects/test/node_modules/glob with version  5.0.15 will be replaced with dependency located at /home/na3r/projects/test/node_modules/nativescript-hook/node_modules/glob with version 6.0.4
Successfully prepared plugin nativescript-cache for android.
Successfully prepared plugin nativescript-cardview for android.
Successfully prepared plugin nativescript-sqlite for android.
Successfully prepared plugin nativescript-statusbar for android.
Successfully prepared plugin nativescript-telerik-ui for android.
Successfully prepared plugin tns-core-modules for android.
Project successfully prepared
Executing after-prepare hook from /home/na3r/projects/test/hooks/after-prepare/nativescript-dev-babel.js
Processing complete

:config phase:  createDefaultIncludeFiles
	+found plugins: nativescript-cardview

:config phase:  createPluginsConfigFile
	+creating product flavors include.gradle file in configurations folder...

:config phase:  pluginExtend
	+applying configuration from: /home/na3r/projects/test/platforms/android/configurations/include.gradle
	+applying configuration from: /home/na3r/projects/test/platforms/android/configurations/nativescript-cardview/include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
	+adding dependency: /home/na3r/projects/test/platforms/android/libs/aar/Chart-2015.3.1307-trial-release.aar
	+adding dependency: /home/na3r/projects/test/platforms/android/libs/aar/Data-2015.3.1307-trial-release.aar
	+adding dependency: /home/na3r/projects/test/platforms/android/libs/aar/List-2015.3.1307-trial-release.aar
	+adding dependency: /home/na3r/projects/test/platforms/android/libs/aar/Common-2015.3.1307-trial-release.aar
	+adding dependency: /home/na3r/projects/test/platforms/android/libs/aar/Primitives-2015.3.1307-trial-release.aar
	+adding dependency: /home/na3r/projects/test/platforms/android/libs/aar/widgets-release.aar
	+adding dependency: /home/na3r/projects/test/platforms/android/libs/aar/Input-2015.3.1307-trial-release.aar
:preBuild UP-TO-DATE
:preNativescriptcardviewDebugBuild UP-TO-DATE
:checkNativescriptcardviewDebugManifest
:preNativescriptcardviewReleaseBuild UP-TO-DATE
:prepareChart201531307TrialReleaseLibrary
:prepareComAndroidSupportAppcompatV72311Library
:prepareComAndroidSupportCardviewV72311Library
:prepareComAndroidSupportSupportV42311Library
:prepareCommon201531307TrialReleaseLibrary
:prepareData201531307TrialReleaseLibrary
:prepareInput201531307TrialReleaseLibrary
:prepareList201531307TrialReleaseLibrary
:preparePrimitives201531307TrialReleaseLibrary
:prepareWidgetsReleaseLibrary
:prepareNativescriptcardviewDebugDependencies
:compileNativescriptcardviewDebugAidl
:compileNativescriptcardviewDebugRenderscript
:generateNativescriptcardviewDebugBuildConfig
:generateNativescriptcardviewDebugAssets UP-TO-DATE
:mergeNativescriptcardviewDebugAssets
:generateNativescriptcardviewDebugResValues
:generateNativescriptcardviewDebugResources
:mergeNativescriptcardviewDebugResources
:processNativescriptcardviewDebugManifest
:processNativescriptcardviewDebugResources
:generateNativescriptcardviewDebugSources
:compileNativescriptcardviewDebugJavaWithJavac
:compileNativescriptcardviewDebugNdk UP-TO-DATE
:compileNativescriptcardviewDebugSources
:cleanLocalAarFiles
:ensureMetadataOutDir
:collectAllJars
:buildMetadata
Skip com.telerik.android.primitives.widget.sidedrawer.BlurFadeLayer
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.DeckOfCardsLayoutManager
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.FadeItemAnimator
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.ItemAnimatorSet
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.ListViewItemAnimator
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.ListViewItemAnimator$ChangeInfo
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.ListViewItemAnimator$MoveInfo
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.RadListView
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.ScaleItemAnimator
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.SlideItemAnimator
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.SlideLayoutManagerBase
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.WrapLayoutManager
	Error: java.lang.NullPointerException
 'assets/metadata/treeNodeStream.dat' NOT FOUND
 'assets/metadata/treeStringsStream.dat' NOT FOUND
 'assets/metadata/treeValueStream.dat' NOT FOUND
 'assets/metadata/treeNodeStream.dat'...
 'assets/metadata/treeStringsStream.dat'...
 'assets/metadata/treeValueStream.dat'...
:transformClassesWithDexForNativescriptcardviewDebug
:mergeNativescriptcardviewDebugJniLibFolders
:transformNative_libsWithMergeJniLibsForNativescriptcardviewDebug
:processNativescriptcardviewDebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForNativescriptcardviewDebug
:validateDebugSigning
:packageNativescriptcardviewDebug
:zipalignNativescriptcardviewDebug
:assembleNativescriptcardviewDebug
:assembleDebug
:deleteExplodedAarFolder
:buildapk

BUILD SUCCESSFUL

Total time: 32.883 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.8/userguide/gradle_daemon.html
Project successfully built
Successfully deployed on device with identifier '0a484af4'.
03-28 11:43:16.529 10402 10402 F art     : art/runtime/java_vm_ext.cc:410]     from java.lang.Object com.tns.Platform.callJSMethodNative(int, java.lang.String, int, boolean, java.lang.Object[])
03-28 11:43:16.529 10402 10402 F art     : art/runtime/java_vm_ext.cc:410]   at com.tns.Platform.callJSMethodNative(Native method)
03-28 11:43:16.529 10402 10402 F art     : art/runtime/java_vm_ext.cc:410]   at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:816)
03-28 11:43:16.529 10402 10402 F art     : art/runtime/java_vm_ext.cc:410]   at com.tns.Platform.callJSMethod(Platform.java:715)
03-28 11:43:16.529 10402 10402 F art     : art/runtime/java_vm_ext.cc:410]   at com.tns.Platform.callJSMethod(Platform.java:694)
03-28 11:43:16.529 10402 10402 F art     : art/runtime/java_vm_ext.cc:410]   at com.tns.Platform.callJSMethod(Platform.java:684)
03-28 11:43:16.824 10402 10402 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.callJSMethodNative(Native method)
03-28 11:43:16.824 10402 10402 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:816)
03-28 11:43:16.824 10402 10402 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.callJSMethod(Platform.java:715)
03-28 11:43:16.824 10402 10402 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.callJSMethod(Platform.java:694)
03-28 11:43:16.824 10402 10402 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.callJSMethod(Platform.java:684)
03-28 11:43:16.825 10402 10402 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.callJSMethodNative(Native method)
03-28 11:43:16.825 10402 10402 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:816)
03-28 11:43:16.825 10402 10402 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.callJSMethod(Platform.java:715)
03-28 11:43:16.825 10402 10402 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.callJSMethod(Platform.java:694)
03-28 11:43:16.825 10402 10402 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.callJSMethod(Platform.java:684)
03-28 11:43:20.377 10563 10563 F art     : art/runtime/java_vm_ext.cc:410]     from java.lang.Object com.tns.Platform.callJSMethodNative(int, java.lang.String, int, boolean, java.lang.Object[])
03-28 11:43:20.377 10563 10563 F art     : art/runtime/java_vm_ext.cc:410]   at com.tns.Platform.callJSMethodNative(Native method)
03-28 11:43:20.377 10563 10563 F art     : art/runtime/java_vm_ext.cc:410]   at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:816)
03-28 11:43:20.378 10563 10563 F art     : art/runtime/java_vm_ext.cc:410]   at com.tns.Platform.callJSMethod(Platform.java:715)
03-28 11:43:20.378 10563 10563 F art     : art/runtime/java_vm_ext.cc:410]   at com.tns.Platform.callJSMethod(Platform.java:694)
03-28 11:43:20.378 10563 10563 F art     : art/runtime/java_vm_ext.cc:410]   at com.tns.Platform.callJSMethod(Platform.java:684)
03-28 11:43:20.677 10563 10563 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.callJSMethodNative(Native method)
03-28 11:43:20.677 10563 10563 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:816)
03-28 11:43:20.677 10563 10563 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.callJSMethod(Platform.java:715)
03-28 11:43:20.678 10563 10563 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.callJSMethod(Platform.java:694)
03-28 11:43:20.678 10563 10563 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.callJSMethod(Platform.java:684)
03-28 11:43:20.678 10563 10563 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.callJSMethodNative(Native method)
03-28 11:43:20.678 10563 10563 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:816)
03-28 11:43:20.678 10563 10563 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.callJSMethod(Platform.java:715)
03-28 11:43:20.678 10563 10563 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.callJSMethod(Platform.java:694)
03-28 11:43:20.678 10563 10563 F art     : art/runtime/runtime.cc:366]   at com.tns.Platform.callJSMethod(Platform.java:684)

any idea?

**Comment by ginev** [comment]
@na3r it seems native RadListView types are not there. Based on the stack trace I cannot exactly say what causes this. My advice is to remove the nativescript-telerik-ui plugin, delete the platforms folder and read it again. Also, make sure to follow the Getting started instructions from start to end .

**Comment by na3r** [comment]
@ginev i removed nativescript-telerik-ui plugin, android platform as well as node_modules directory and reinstalled them again. but i get the same error

steps i've done are as follow:

tns plugin remove nativescript-telerik-ui
tns platform remove android
rm -rf node_modules
tns plugin add nativescript-telerik-ui
tns platform add android
npm install

**Comment by ginev** [comment]
Can you paste the XML file of your page?
