### ISSUE TITLE
RadCalendar : Disable some Date in Calendar ?

### ISSUE THREAD

**Issue by yezarela** [telerik/nativescript-ui-samples#86]
Is it possible to disable some/past dates ?

**Comment by yezarela** [comment]
It seems to use minDate, maxDate property of radCalendar..
`radCalendar = <calendarModule.RadCalendar>page.getViewById("calendar");`
`var DateStartDate: Date = new Date(startDate);`
`radCalendar.minDate = DateStartDate;`

But, it doesn't make any changes, any suggestion ?

**Comment by karaahmed** [comment]
Hi yezarela,

you are right, this is a bug we've fixed for next updated.
If it is critical for you, you can easily fix it in your local 
**node_modules/nativescript-telerik-ui/calendar** copy of the plugin.
Just replace fybctuib banes 
_onMinDatePropertyChanged_ to _onMinDateChanged_
and 
_onMaxDatePropertyChanged_ to _onMaxDateChanged_

in files: calendar.ios.js & calendar.android.js

Please, let me know if you have any other questions.

**Comment by yezarela** [comment]
Thanks @karaahmed , It worked as expected !

But, When I tried to get "DateRange" property from radCalendar, 
"startDate" property returns wrong date,
Is this also a bug ?

**Comment by karaahmed** [comment]
Can you give me more information, what exactly your case is.
I can suggest that you make a selection and try to get the _selectedDateRange_ property to get info about selection. Am I right?

**Comment by yezarela** [comment]
Yes, you're absolutely right,

Case 1:
When I select date from **March 14, 2016** to **March 17, 2016**  by selecting _startDate_ first then _endDate,_ calendar returns _selectedDateRange_ with value:

- _startDate_ : March 15, 2016

- _endDate_ : March 17, 2016

Case 2:
When I select date from **March 14, 2016** to **March 17, 2016**  by selecting _endDate_ first then _startDate,_ calendar returns _selectedDateRange_ with value:

- _startDate_ : March 14, 2016

- _endDate_ : March 16, 2016

_*selecting = touching = clicking_

**Comment by karaahmed** [comment]
Can you tell me the time zone of the calendar you use. I think it should be something related to the synchronization of ±Hours related to the time zone.

**Comment by yezarela** [comment]
My current time zone is **UTC + 7**

**Comment by karaahmed** [comment]
It looks like this is a bug of our native iOS calendar component.
We logged it and will fix it asap.

**Comment by yezarela** [comment]
Hi @karaahmed , the bug is only happen on Android
