### ISSUE TITLE
nativescript-ui seems not to be compatible with nativescript :D (2.0.0)

### ISSUE THREAD

**Issue by AntonTrapp** [telerik/nativescript-ui-samples#87]
```tns plugin add nativescript-telerik-ui```

```
:buildMetadata
Exception in thread "main" java.lang.IllegalArgumentException: Class com.tns.internal.AppBuilderCallback conflict: /Users/atrapp/development/sCAD2016mobile/platforms/android/build/intermediates/classes/F0F1/debug and /Users/atrapp/development/sCAD2016mobile/platforms/android/build/intermediates/classes/F0/debug
	at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
	at com.telerik.metadata.Builder.build(Builder.java:42)
	at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

FAILURE: Build failed with an exception.
```

Removing the plugin again leads to:

```
/Users/atrapp/development/sCAD2016mobile/platforms/android/src/main/java/com/tns/gen/com/telerik/widget/list/ReorderWithHandlesBehavior_frnal_ts_helpers_l47_c38__ExtendedReorderWithHandlesBehavior.java:3: error: package com.telerik.widget.list does not exist
public class ReorderWithHandlesBehavior_frnal_ts_helpers_l47_c38__ExtendedReorderWithHandlesBehavior extends com.telerik.widget.list.ReorderWithHandlesBehavior implements com.tns.NativeScriptHashCodeProvider {
                                                                                                                                    ^
/Users/atrapp/development/sCAD2016mobile/platforms/android/src/main/java/com/tns/gen/com/telerik/widget/list/ReorderWithHandlesBehavior_frnal_ts_helpers_l47_c38__ExtendedReorderWithHandlesBehavior.java:15: error: package com.telerik.widget.list does not exist
	public void onAttached(com.telerik.widget.list.RadListView param_0)  {
	                                              ^
/Users/atrapp/development/sCAD2016mobile/platforms/android/src/main/java/com/tns/gen/com/telerik/widget/list/ReorderWithHandlesBehavior_frnal_ts_helpers_l47_c38__ExtendedReorderWithHandlesBehavior.java:22: error: cannot find symbol
		return super.equals(other);
		       ^
  symbol:   variable super
  location: class ReorderWithHandlesBehavior_frnal_ts_helpers_l47_c38__ExtendedReorderWithHandlesBehavior
/Users/atrapp/development/sCAD2016mobile/platforms/android/src/main/java/com/tns/gen/com/telerik/widget/list/ReorderWithHandlesBehavior_frnal_ts_helpers_l47_c38__ExtendedReorderWithHandlesBehavior.java:26: error: cannot find symbol
		return super.hashCode();
		       ^
  symbol:   variable super
  location: class ReorderWithHandlesBehavior_frnal_ts_helpers_l47_c38__ExtendedReorderWithHandlesBehavior
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors
:compileF0DebugJavaWithJavac FAILED
``

**Comment by 3logy** [comment]
Same here. Im trying to reproduce the "Groceries App" with TNS 2.0 and Typescript 1.8. It's worked since i add the "npm i nativescript-telerik-ui". I can't successful build the android platform. i must remove the telerik ui and remove the android platform and re add android platform to make my app run again.

**Comment by Daxito** [comment]
It works for me, using {N} 2.0.1 and version of nativescript-telerik-ui 1.1.1 though

**Comment by mi6crazyheart** [comment]
Same with me also. Build failed after adding this plugin. 

![nativescript-build-failed](https://cloud.githubusercontent.com/assets/4346688/16170681/6d07ff72-3579-11e6-9265-a239c6e781de.png)

My package.json file

	{
	  "description": "NativeScript Application",
	  "license": "SEE LICENSE IN <your-license-filename>",
	  "readme": "NativeScript Application",
	  "repository": "<fill-your-repository-here>",
	  "nativescript": {
	    "id": "org.nativescript.bhramaan",
	    "tns-android": {
	      "version": "2.0.0"
	    }
	  },
	  "dependencies": {
	    "@angular/common": "2.0.0-rc.1",
	    "@angular/compiler": "2.0.0-rc.1",
	    "@angular/core": "2.0.0-rc.1",
	    "@angular/http": "2.0.0-rc.1",
	    "@angular/platform-browser": "2.0.0-rc.1",
	    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
	    "@angular/platform-server": "2.0.0-rc.1",
	    "@angular/router-deprecated": "2.0.0-rc.1",
	    "nativescript-angular": "0.1.1",
	    "nativescript-plugin-firebase": "^3.0.1",
	    "nativescript-telerik-ui": "^1.1.1",
	    "tns-core-modules": "^2.0.0"
	  },
	  "devDependencies": {
	    "babel-traverse": "6.9.0",
	    "babel-types": "6.9.0",
	    "babylon": "6.8.0",
	    "filewalker": "0.1.2",
	    "lazy": "1.0.11",
	    "nativescript-dev-typescript": "^0.3.2",
	    "typescript": "^1.8.10"
	  }
	}

Then, after removing the plugin I'm getting same error like @AntonTrapp

**Comment by mi6crazyheart** [comment]
Got one  workaround to solve this issue. Here are the steps.

- Don't remove the plugin
- Remove the platform(android/ios)
- Add the platform once again(android/ios)
- Rebuild the app

In my case, after following these steps I'm not getting any build error.

**Comment by MiroValchev** [comment]
Works fine with {N} 2.1.
