### ISSUE TITLE
Swipe to open drawer and swipe to go back on iOS

### ISSUE THREAD

**Issue by firecube** [telerik/nativescript-ui-samples#88]
Hi,

Due to the swipe to go back feature of iOS I am getting some odd behaviour on an iPhone 6s.  I am able to swipe and open the menu but also see the page sliding out with the previous page behind both at the same time.  This looks odd.

I was able to prevent the swipe to go back by adding this line to all of the pages with the drawer...

topmost().ios.controller.interactivePopGestureRecognizer.enabled = false;

Unfortunately this has meant that when I navigate through these main pages the swipe to open the drawer stops working.

I tried to force the drawer swipe by doing the following but it didn't work.  

var drawer = <RadSideDrawer>page.getViewById('drawer');
if (drawer) {
      drawer.gesturesEnabled = true;
}

Does anyone know how I can handle this?

Thanks, Simon

**Comment by guliashki** [comment]
Hi, Simon,

Possible solution is to set a treshold that will allow opening the drawer from inside the main view. This property is still not exposed in the NativeScript component so you should set it through its ios property. Consider the code below:
`sideDrawer.ios.teshold = 100;`

**Comment by firecube** [comment]
Hi,

Can you explain what I am setting here?  What is that variable doing? 

Thanks, Simon

**Comment by guliashki** [comment]
Hi, Simon,

This property is used to change the area from the edge of the screen that will fire the gesture recognizer used to open the side drawer.

**Comment by Natalia-Hristova** [comment]
Hello @firecube , 

All issues here will be moved (if they are still valid) and closed because this repository is only for examples.

If you have any feedback, issues or feature requests please log them in [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback) repository.

Thank you in advance!
