### ISSUE TITLE
JS: Binding: Property: 'name' is invalid or does not exist. SourceProperty: 'name'

### ISSUE THREAD

**Issue by nicHoch** [telerik/nativescript-ui-samples#89]
Hi 

I am using the RadListView. For each property that is bind in the itemTemplate via xml (text = "{{ name }}") an error is logged to the console: 

`JS: Binding: Property: 'name' is invalid or does not exist. SourceProperty: 'name'.`

But an name property exists and the rendering of the UI is working well and everything is shown. Due to the massive logging the app is a bit slow. Any ideas what is wrong?

Nicky

**Comment by patuku-roy** [comment]
I can confirmed this problem happened on my side too ...

**Comment by kwong93** [comment]
Also getting this problem, everything loads fine, just bunch of console errors

**Comment by Premitium** [comment]
Also happens to me after updating to 2.01 from 1.6 {N}.
