### ISSUE TITLE
Implement a way for the sidedrawer to overlap the action bar

### ISSUE THREAD

**Issue by lscown** [telerik/nativescript-ui-samples#9]
Hey!

Currently, the sidedrawer appears under the action bar, making the action bar always visible. Would be great to see this overlay the action bar like it does with most iOS and Android apps.

Reference: https://groups.google.com/forum/#!topic/nativescript/tMZCwHP3Ko8

**Comment by ginev** [comment]
Hi @lscown,

This is a known limitation and it is being worked on.

**Comment by maknz** [comment]
Hi guys, any update on this?

**Comment by dapriett** [comment]
+1

**Comment by alexrainman** [comment]
+1

**Comment by stevetayloruk** [comment]
+1

**Comment by sitefinitysteve** [comment]
I just encountered this as well... Itd be embarassing to deliver the app looking like this :/

**Comment by treio** [comment]
+1

**Comment by tjvantoll** [comment]
+1 from me as well. I was surprised this isn’t available out of the box.

**Comment by sitefinitysteve** [comment]
@tjvantoll is actually more shocking than surprising... When one thinks of a sidebar one never expects it to be below the nav. Kinda throws a big monkey wrench into app dev. One plans for a sidebar but after you see it, have to sit down to talk about plan b :/

**Comment by dapriett** [comment]
Yeah, I've had to ditch the ActionBar control, and just create a custom NavBar that I can put inside the SideDrawer mainContent.  Would be nice to be able to use the ActionBar and SideBar together.

**Comment by sitefinitysteve** [comment]
I'm just thinking of the user who shells out the $$ to buy the suite when available, maybe the drawer is the component they are buying it for... and it's totally unusable.

I had to refactor my entire UI to compensate for this, I mean I ultimatly ended up with a better solution I think, but still the drawer would have been coooool.

**Comment by ginev** [comment]
Hello @sitefinitysteve ,
Thanks for your feedback! Although the drawer will be free of charge, we're still comitted to uprading it as requested here. Since the way the ActionBar is implemented in NativeScript prevents us from being able to show over it, we're currently figuring out what's the best way to do it in a reasonable manner. Stay tuned.

**Comment by ginev** [comment]
@dapriett ,

That's exactly what we're considering. Currently the Page.actionBar property is what defines the UINavigationBar on iOS or ActionBar/ToolBar on Android. This is not a separate View in NativeScript but a property of the Page. In that respect, we're not able to simply put it in the `mainContent` of the drawer. The idea here is to wrap the UINavigationBar and ToolBar with a NativeScript view which then will be place as a child of the SideDrawer.

**Comment by toddanglin** [comment]
Any update on this issue? Now that UI for NativeScript is available, a fix is more urgent.

**Comment by terreb** [comment]
+1

**Comment by aandino-dev** [comment]
isn't implemented yet? Because the preview photo showed on [npm](https://www.npmjs.com/package/nativescript-telerik-ui) look like a yes or this preview photo isn't write it in nativescript?

**Comment by bradmartin** [comment]
http://docs.telerik.com/devtools/nativescript-ui/api/classes/radsidedrawer.html#showovernavigation

I tried and it does work but there seems to be some minor bugs with the layout of it. There was a small gap from the bottom of drawer and the bottom or app screen. I'll get screens and get bugs filed later.

**Comment by naderio** [comment]
I tried the `showOverNavigation` option too and I found the same issue as noted by @bradmartin + the overlay remains on top of view after navigation

**Comment by spstratis** [comment]
+ 1 I too get a black overlay over the screen when I navigate to another view along with the Gap that appears on the bottom.

**Comment by ginev** [comment]
Hello to everyone,

A quick update on the status of this:
We are already done with this feature for iOS. We are working on the Android implementation which turned out to be trickier because of status bar and software navigation buttons on some Android devices.
We hope that we will be ready with the feature by the end of June.

**Comment by spstratis** [comment]
Hi @ginev  

It looks like there was a new release of the nativescript-ui. Was this part update part of it?

**Comment by hchor** [comment]
http://docs.telerik.com/devtools/nativescript-ui/release-notes

Doesn't look like it. Only iOS.

**Comment by Gustavo47** [comment]
+ 1 for android ;-)

**Comment by kozakvoj** [comment]
+1

**Comment by tjvantoll** [comment]
Just fyi, this feature has been implemented in the latest release of UI for {N}. See http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/SideDrawer/getting-started#showing-radsidedrawer-over-the-navigation-baraction-bar 🎉

**Comment by kozakvoj** [comment]
@tjvantoll Nice, thanks for the info. Do you also have a guide for Angular, please?

**Comment by tjvantoll** [comment]
@kozakvoj: Hmmm... not sure whether that’s supported yet or not. I’m not seeing the information listed on http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/SideDrawer/getting-started. @ginev: is this supported yet in ng2 apps?

**Comment by VladimirAmiorkov** [comment]
@tjvantoll Idd this feature is still not available in {N} Angular apps. You can follow [this](https://github.com/telerik/nativescript-ui-samples-angular/issues/26) logged issue for future updates.

**Comment by vjoao** [comment]
Hello, this may be an even trickier one: How can I put the side drawer above / behind the statusbar (per Material Design spec)?

This is implemented on google apps like Gmail (that neat side drawer).

**Comment by VladimirAmiorkov** [comment]
@vjoao Take a look at this message https://github.com/telerik/nativescript-ui-samples/issues/112#issuecomment-251414359
