### ISSUE TITLE
Side drawer position

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-samples#90]
_From @Pip3r4o on May 18, 2016 20:25_

_From @eduardoturconi on May 18, 2016 19:16_

Hello.

I'm trying to use the RadSideDrawer from Telerik NativeScript UI, the code is almost exactly to the one provided in telerik docs.
But, when I set the property showOverNavigation to true, the layout becomes like this:
![screenshot_20160518-161113](https://cloud.githubusercontent.com/assets/4389868/15371815/b82e7892-1d13-11e6-9c31-62f1434efc18.png)

As you can see, the side drawer and status bar top are equal, and there's a strange margin with the same size than status bar's height on the bottom of the side drawer.
I'm using nativescript version 2.0

_Copied from original issue: NativeScript/android-runtime#458_

_Copied from original issue: NativeScript/NativeScript#2141_

**Comment by ginev** [comment]
@tsonevn An improved SideDrawer is coming in terms of supporting the over-the-actionbar behavior. This glitch will be addressed there.

**Comment by eduardoturconi** [comment]
I think vertical margin is wrong (margin is placed in bottom), and I was able to address this issue by doing:

	radSideDrawer = <RadSideDrawer>(<View>stackLayout).parent;

	if(radSideDrawer.android) {
		var layoutParams = radSideDrawer.drawerContent.android.getLayoutParams();
		layoutParams.topMargin = layoutParams.bottomMargin;
		layoutParams.bottomMargin = 0;
		radSideDrawer.drawerContent.android.setLayoutParams(layoutParams);
	}

**Comment by ginev** [comment]
@eduardoturconi, this sounds like a possible solution but I recommend testing on different Android API levels as this behavior is not consistent over the Android version palette.
