### ISSUE TITLE
Attempt to invoke virtual method void android.view.View.bringToFront() on a null object

### ISSUE THREAD

**Issue by Daxito** [telerik/nativescript-ui-samples#95]
Hi, 
I am using the Pro Version 1.1.1 and my exception logs sometimes log this error, I am not able to duplicate this myself but I hope you can give some clue about what could be happening with this SideDrawer.

{
  "nativeException": {

  },
  "stackTrace": "java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.bringToFront()' on a null object reference\n\tat com.telerik.android.primitives.widget.sidedrawer.transitions.DrawerTransitionBase.setProgress(DrawerTransitionBase.java:77)\n\tat com.telerik.android.primitives.widget.sidedrawer.transitions.DrawerTransitionBase.onEnded(DrawerTransitionBase.java:230)\n\tat com.telerik.android.primitives.widget.sidedrawer.transitions.DrawerTransitionBase.run(DrawerTransitionBase.java:221)\n\tat android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1121)\n\tat android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1171)\n\tat android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:722)\n\tat android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:738)\n\tat android.view.Choreographer$CallbackRecord.run(Choreographer.java:798)\n\tat android.view.Choreographer.doCallbacks(Choreographer.java:611)\n\tat android.view.Choreographer.doFrame(Choreographer.java:580)\n\tat android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:784)\n\tat android.os.Handler.handleCallback(Handler.java:739)\n\tat android.os.Handler.dispatchMessage(Handler.java:95)\n\tat android.os.Looper.loop(Looper.java:135)\n\tat android.app.ActivityThread.main(ActivityThread.java:5254)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat java.lang.reflect.Method.invoke(Method.java:372)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)\n"
}

**Comment by Daxito** [comment]
UPDATE:
I was able to duplicate the issue, please see the attached App, I removed the platform and modules files so you just need to re-install.
The App consists of two pages, Page 1 takes you to Page2 where the SideDrawer is located, I open the SideDrawer and then I click a button to close it and right after closing I navigate back to Page1, error occurs when Navigating back:

[SampleApp3.zip](https://github.com/telerik/nativescript-ui-samples/files/287423/SampleApp3.zip)

**Comment by Daxito** [comment]
This issue is easy to duplicate by just running the attached App :-(

**Comment by sax1johno** [comment]
+1 Having the same issue as well. It only happens when transitioning to an activity using frame.topmost().navigate from within the side bar.  I have the same exact code being triggered from a button that's not in the sidebar and do not experience this issue.

**Comment by sax1johno** [comment]
@Daxito I was able to replicate the issue and have developed a workaround.  The problem occurs when you attempt to navigate to another activity before the side drawer transition has completed.  The transition lifecycle is disrupted and attempts to call the "transitionEnd" method on a non-existent side drawer.

This only happens if you DON'T have the sidebar in the page you're transitioning to - ie: if there's no side drawer for the transition lifecycle methods to attach to.

The workaround is to close the drawer first, and then perform your navigation in the onDrawerClosed event method.

ex:

```drawerPage.xml
  <drawer:rad-side-drawer 
    id="drawer"
    drawerClosed="onDrawerClosed"
  >
....
</drawer:rad-side-drawer>
```

and then in your javascript:

```javascript
var command;

exports.selectDrawerItem = function(args) {
    drawer.selectDrawerItem(args, function(item) {
        var tag = item.object.tag;
        command = tag;
        drawer.closeDrawer();
    });
}

exports.onDrawerClosed = function() {
    switch (command) {
        case "goToBrowse":
            frame.topmost().navigate({
                moduleName: "views/searchByTag/searchByTag",
            })
            break;
        .... etc
    }
}
```

Note for anyone working on this issue: This issue does NOT arise in iOS - only in Android.

**Comment by Daxito** [comment]
@sax1johno I will take a look at the workaround, thanks!

**Comment by jwuliger** [comment]
Hello. I am having an issue similar to this. Can you please take a look at the issue located here?:

https://github.com/NativeScript/nativescript-angular/issues/388

Thanks so much for any help!

**Comment by ginev** [comment]
This issue was moved to telerik/nativescript-ui-feedback#121
