### ISSUE TITLE
RadListView not working for ios

### ISSUE THREAD

**Issue by Daxito** [telerik/nativescript-ui-samples#99]
Please take a look at the attached project,

[DemoApp.zip](https://github.com/telerik/nativescript-ui-samples/files/348725/DemoApp.zip)

 the radlistview just doesn't work for ios, nothing renders and the log says:

Jul  5 16:54:57 Jacks-MacBook-Air-2 httpdemo[9431]: CONSOLE WARN file:///app/tns_modules/nativescript-telerik-ui/listview/listview.js:370:14: The TypeScript constructor "TKListViewDataSourceImpl" will not be executed.
Jul  5 16:54:57 Jacks-MacBook-Air-2 httpdemo[9431]: CONSOLE WARN file:///app/tns_modules/nativescript-telerik-ui/listview/listview.js:509:14: The TypeScript constructor "ExtendedListViewCell" will not be executed.

Please advice

**Comment by ginev** [comment]
@Daxito, just remove the StackLayout as root layout or simply assign height to it.

**Comment by Daxito** [comment]
@ginev I will try that, thank you!

**Comment by Daxito** [comment]
Worked @ginev !

Thanks
